#!/usr/bin/env python3
"""Build square list thumbnails for every species photo and the lookup table
the app uses to bundle them.

Reads:   app/assets/data/species-na.json (image URLs from Commons)
Caches:  tools/data/thumbs-src/<code>.<ext>   (downloaded 320px versions, gitignored)
Writes:  app/assets/thumbs/<code>.jpg          (144x144 JPEG, center-cropped)
         app/src/assets/thumbs.ts               (code -> require() map)

Uses macOS `sips` for resizing and cropping, so no Python imaging library is needed.
"""
import json, pathlib, re, subprocess, sys, time, urllib.request, urllib.error

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACK = ROOT / "app/assets/data/species-na.json"
SRC = ROOT / "tools/data/thumbs-src"
OUT = ROOT / "app/assets/thumbs"
MAP = ROOT / "app/src/data/thumbs.ts"
UA = "FluttrSpeciesPackBuilder/0.2 (bird watching app data build)"
SRC_WIDTH = 320
SIZE = 144
QUALITY = 72

# Wikimedia allows 10 requests/minute for clients whose User-Agent has no contact info,
# and 200/minute when it does. Put a contact (URL or email) in UA to run ~20x faster.
DELAY = 6.5
_last = 0.0

def clean(url):
    """Drop the tracking query the API appends; Commons rejects it on new renditions."""
    return url.split("?")[0]

def source_url(url):
    """Ask Commons for a smaller rendition; thumbnail URLs carry their width in the path."""
    return re.sub(r"/\d+px-", "/%dpx-" % SRC_WIDTH, clean(url), count=1)

def fetch(url):
    """Paced GET. Returns bytes, or None on a hard failure. Backs off a full minute on 429."""
    global _last
    for attempt in range(5):
        wait = DELAY - (time.time() - _last)
        if wait > 0:
            time.sleep(wait)
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                data = r.read()
            _last = time.time()
            return data
        except urllib.error.HTTPError as e:
            _last = time.time()
            if e.code == 429:
                print("  429, backing off 60s", flush=True)
                time.sleep(60)
                continue
            if e.code >= 500:
                time.sleep(5 * (attempt + 1))
                continue
            return None
        except Exception:
            time.sleep(3 * (attempt + 1))
    return None

def download(code, url):
    path = url.split("?")[0].lower()
    ext = ".png" if path.endswith((".png", ".svg")) else ".gif" if path.endswith(".gif") else ".jpg"
    dest = SRC / (code + ext)
    if dest.exists() and dest.stat().st_size > 0:
        return dest
    data = fetch(source_url(url)) or fetch(clean(url))
    if not data:
        return None
    dest.write_bytes(data)
    return dest

def sips(*args):
    try:
        return subprocess.run(["sips", *args], capture_output=True, text=True, timeout=30)
    except subprocess.TimeoutExpired:
        return subprocess.CompletedProcess(args, 1, "", "timeout")

def dims(path):
    r = sips("-g", "pixelWidth", "-g", "pixelHeight", str(path))
    m = re.findall(r"pixel(Width|Height): (\d+)", r.stdout)
    d = {k: int(v) for k, v in m}
    return d.get("Width"), d.get("Height")

def make_thumb(src, dest):
    w, h = dims(src)
    if not w or not h:
        return False
    # Scale so the short side is SIZE, then center-crop to a square.
    scale = ["--resampleWidth", str(SIZE)] if w <= h else ["--resampleHeight", str(SIZE)]
    r = sips(*scale, "-s", "format", "jpeg", "-s", "formatOptions", str(QUALITY), str(src), "--out", str(dest))
    if r.returncode != 0:
        return False
    r = sips("-c", str(SIZE), str(SIZE), str(dest))
    return r.returncode == 0 and dest.exists()

def write_map():
    codes = sorted(p.stem for p in OUT.glob("*.jpg"))
    lines = ["// Generated by tools/build_thumbnails.py. Do not edit by hand.",
             "// Square list thumbnails, %dpx, bundled with the app so lists work offline." % SIZE,
             "export const THUMBS: Record<string, number> = {"]
    lines += ["  %s: require('@/assets/thumbs/%s.jpg')," % (c if re.match(r"^[a-z_][a-z0-9_]*$", c) else "'%s'" % c, c) for c in codes]
    lines.append("};\n")
    MAP.parent.mkdir(parents=True, exist_ok=True)
    MAP.write_text("\n".join(lines))
    return codes

def main():
    species = json.loads(PACK.read_text())["species"]
    SRC.mkdir(parents=True, exist_ok=True)
    OUT.mkdir(parents=True, exist_ok=True)
    todo = [(s["code"], s["image"]["url"]) for s in species if s.get("image") and not (OUT / (s["code"] + ".jpg")).exists()]
    print("species with photos: %d, thumbnails to build: %d" % (sum(1 for s in species if s.get("image")), len(todo)), flush=True)

    failed = []
    write_map()  # so the app can use whatever is already built while this runs
    for n, (code, url) in enumerate(todo, 1):
        src = download(code, url)
        if not src or not make_thumb(src, OUT / (code + ".jpg")):
            failed.append(code)
        if n % 100 == 0:
            write_map()
            print("  %d/%d (failed so far: %d)" % (n, len(todo), len(failed)), flush=True)

    codes = write_map()
    total = sum(p.stat().st_size for p in OUT.glob("*.jpg"))
    print("done. thumbnails: %d (%.1f MB); failed: %d %s" % (len(codes), total / 1e6, len(failed), failed[:20]), flush=True)

if __name__ == "__main__":
    main()
