-- Notifications v1: an activity list per user, filled by triggers, and device tokens for push.
-- A trigger calls the `push` Edge Function through pg_net for each new notification.

create extension if not exists pg_net with schema extensions;

-- Species names, so server-side messages can say "your Blue Jay" instead of a code.
create table if not exists public.species_names (
  code        text primary key,
  common_name text not null
);
alter table public.species_names enable row level security;
create policy "species names are public" on public.species_names for select to authenticated using (true);
insert into public.species_names (code, common_name) values
('higtin1', 'Highland Tinamou'),
('gretin1', 'Great Tinamou'),
('littin1', 'Little Tinamou'),
('thitin1', 'Thicket Tinamou'),
('slbtin1', 'Slaty-breasted Tinamou'),
('chotin1', 'Choco Tinamou'),
('wfwduc1', 'White-faced Whistling-Duck'),
('bbwduc', 'Black-bellied Whistling-Duck'),
('wiwduc1', 'West Indian Whistling-Duck'),
('fuwduc', 'Fulvous Whistling-Duck'),
('empgoo', 'Emperor Goose'),
('snogoo', 'Snow Goose'),
('rosgoo', 'Ross''s Goose'),
('gwfgoo', 'Greater White-fronted Goose'),
('pifgoo', 'Pink-footed Goose'),
('brant', 'Brant'),
('bargoo', 'Barnacle Goose'),
('cacgoo1', 'Cackling Goose'),
('cangoo', 'Canada Goose'),
('hawgoo', 'Hawaiian Goose'),
('mutswa', 'Mute Swan'),
('truswa', 'Trumpeter Swan'),
('tunswa', 'Tundra Swan'),
('whoswa', 'Whooper Swan'),
('comduc3', 'Comb Duck'),
('egygoo', 'Egyptian Goose'),
('musduc', 'Muscovy Duck'),
('wooduc', 'Wood Duck'),
('gargan', 'Garganey'),
('buwtea', 'Blue-winged Teal'),
('cintea', 'Cinnamon Teal'),
('norsho', 'Northern Shoveler'),
('gadwal', 'Gadwall'),
('eurwig', 'Eurasian Wigeon'),
('amewig', 'American Wigeon'),
('layduc', 'Laysan Duck'),
('hawduc', 'Hawaiian Duck'),
('mallar3', 'Mallard'),
('mexduc', 'Mexican Duck'),
('ambduc', 'American Black Duck'),
('motduc', 'Mottled Duck'),
('whcpin', 'White-cheeked Pintail'),
('norpin', 'Northern Pintail'),
('gnwtea', 'Green-winged Teal'),
('canvas', 'Canvasback'),
('redhea', 'Redhead'),
('rinduc', 'Ring-necked Duck'),
('tufduc', 'Tufted Duck'),
('gresca', 'Greater Scaup'),
('lessca', 'Lesser Scaup'),
('steeid', 'Steller''s Eider'),
('speeid', 'Spectacled Eider'),
('kineid', 'King Eider'),
('comeid', 'Common Eider'),
('harduc', 'Harlequin Duck'),
('sursco', 'Surf Scoter'),
('whwsco2', 'White-winged Scoter'),
('whwsco1', 'Stejneger''s Scoter'),
('blksco2', 'Black Scoter'),
('lotduc', 'Long-tailed Duck'),
('buffle', 'Bufflehead'),
('comgol', 'Common Goldeneye'),
('bargol', 'Barrow''s Goldeneye'),
('smew', 'Smew'),
('hoomer', 'Hooded Merganser'),
('commer', 'Common Merganser'),
('rebmer', 'Red-breasted Merganser'),
('masduc', 'Masked Duck'),
('rudduc', 'Ruddy Duck'),
('higgua1', 'Highland Guan'),
('blagua1', 'Black Guan'),
('cregua1', 'Crested Guan'),
('horgua1', 'Horned Guan'),
('grecur1', 'Great Curassow'),
('placha', 'Plain Chachalaca'),
('whbcha1', 'White-bellied Chachalaca'),
('wemcha1', 'West Mexican Chachalaca'),
('rubcha1', 'Rufous-bellied Chachalaca'),
('grhcha1', 'Gray-headed Chachalaca'),
('ruvcha1', 'Rufous-vented Chachalaca'),
('helgui', 'Helmeted Guineafowl'),
('tafqua1', 'Tawny-faced Quail'),
('mouqua', 'Mountain Quail'),
('bcwpar1', 'Buffy-crowned Wood-Partridge'),
('ltwpar1', 'Long-tailed Wood-Partridge'),
('bewpar1', 'Bearded Wood-Partridge'),
('banqua1', 'Banded Quail'),
('norbob', 'Northern Bobwhite'),
('bltbob1', 'Black-throated Bobwhite'),
('crebob2', 'Spot-bellied Bobwhite'),
('crebob1', 'Crested Bobwhite'),
('scaqua', 'Scaled Quail'),
('elequa', 'Elegant Quail'),
('calqua', 'California Quail'),
('gamqua', 'Gambel''s Quail'),
('monqua', 'Montezuma Quail'),
('ocequa1', 'Ocellated Quail'),
('sinqua1', 'Singing Quail'),
('mawqua1', 'Marbled Wood-Quail'),
('bewqua1', 'Black-eared Wood-Quail'),
('tawqua1', 'Tacarcuna Wood-Quail'),
('bbwqua1', 'Black-breasted Wood-Quail'),
('spwqua1', 'Spotted Wood-Quail'),
('wiltur', 'Wild Turkey'),
('ocetur1', 'Ocellated Turkey'),
('rufgro', 'Ruffed Grouse'),
('saggro', 'Greater Sage-Grouse'),
('gusgro', 'Gunnison Sage-Grouse'),
('dusgro', 'Dusky Grouse'),
('soogro1', 'Sooty Grouse'),
('shtgro', 'Sharp-tailed Grouse'),
('grpchi', 'Greater Prairie-Chicken'),
('lepchi', 'Lesser Prairie-Chicken'),
('whtpta1', 'White-tailed Ptarmigan'),
('wilpta', 'Willow Ptarmigan'),
('rocpta1', 'Rock Ptarmigan'),
('sprgro', 'Spruce Grouse'),
('grypar', 'Gray Partridge'),
('rinphe1', 'Ring-necked Pheasant'),
('kalphe', 'Kalij Pheasant'),
('compea', 'Indian Peafowl'),
('redjun', 'Red Junglefowl'),
('gryfra', 'Gray Francolin'),
('blkfra', 'Black Francolin'),
('himsno', 'Himalayan Snowcock'),
('japqua', 'Japanese Quail'),
('chukar', 'Chukar'),
('ercfra', 'Erckel''s Spurfowl'),
('rocpig', 'Rock Pigeon'),
('pavpig2', 'Pale-vented Pigeon'),
('scapig2', 'Scaled Pigeon'),
('scnpig1', 'Scaly-naped Pigeon'),
('whcpig2', 'White-crowned Pigeon'),
('rebpig1', 'Red-billed Pigeon'),
('plapig', 'Plain Pigeon'),
('batpig1', 'Band-tailed Pigeon'),
('ritpig', 'Ring-tailed Pigeon'),
('plupig2', 'Plumbeous Pigeon'),
('rudpig', 'Ruddy Pigeon'),
('shbpig', 'Short-billed Pigeon'),
('eucdov', 'Eurasian Collared-Dove'),
('afcdov1', 'African Collared-Dove'),
('spodov', 'Spotted Dove'),
('zebdov', 'Zebra Dove'),
('incdov', 'Inca Dove'),
('cogdov', 'Common Ground Dove'),
('pbgdov1', 'Plain-breasted Ground Dove'),
('rugdov', 'Ruddy Ground Dove'),
('blgdov1', 'Blue Ground Dove'),
('mcgdov1', 'Maroon-chested Ground Dove'),
('bhqdov1', 'Blue-headed Quail-Dove'),
('crqdov1', 'Crested Quail-Dove'),
('ruqdov', 'Ruddy Quail-Dove'),
('viqdov1', 'Violaceous Quail-Dove'),
('gfqdov', 'Gray-fronted Quail-Dove'),
('wfqdov', 'White-fronted Quail-Dove'),
('kwqdov', 'Key West Quail-Dove'),
('brqdov1', 'Bridled Quail-Dove'),
('obqdov1', 'Olive-backed Quail-Dove'),
('whtdov', 'White-tipped Dove'),
('cardov1', 'Caribbean Dove'),
('grcdov1', 'Gray-chested Dove'),
('gyhdov1', 'Gray-headed Dove'),
('gredov1', 'Grenada Dove'),
('tuqdov1', 'Tuxtla Quail-Dove'),
('bfqdov1', 'Buff-fronted Quail-Dove'),
('pbqdov1', 'Purplish-backed Quail-Dove'),
('wfqdov1', 'White-faced Quail-Dove'),
('chqdov1', 'Chiriqui Quail-Dove'),
('rcqdov1', 'Russet-crowned Quail-Dove'),
('whwdov', 'White-winged Dove'),
('zendov', 'Zenaida Dove'),
('eardov1', 'Eared Dove'),
('moudov', 'Mourning Dove'),
('socdov1', 'Socorro Dove'),
('chbsan', 'Chestnut-bellied Sandgrouse'),
('greani1', 'Greater Ani'),
('smbani', 'Smooth-billed Ani'),
('grbani', 'Groove-billed Ani'),
('strcuc1', 'Striped Cuckoo'),
('phecuc1', 'Pheasant Cuckoo'),
('legcuc1', 'Lesser Ground-Cuckoo'),
('lesroa1', 'Lesser Roadrunner'),
('greroa', 'Greater Roadrunner'),
('rvgcuc1', 'Rufous-vented Ground-Cuckoo'),
('litcuc2', 'Little Cuckoo'),
('squcuc2', 'Mexican Squirrel-Cuckoo'),
('squcuc1', 'Common Squirrel-Cuckoo'),
('yebcuc', 'Yellow-billed Cuckoo'),
('mancuc', 'Mangrove Cuckoo'),
('coccuc1', 'Cocos Cuckoo'),
('bkbcuc', 'Black-billed Cuckoo'),
('gyccuc', 'Gray-capped Cuckoo'),
('chbcuc4', 'Chestnut-bellied Cuckoo'),
('babcuc4', 'Bay-breasted Cuckoo'),
('jamlic1', 'Jamaican Lizard-Cuckoo'),
('purlic1', 'Puerto Rican Lizard-Cuckoo'),
('grelic1', 'Great Lizard-Cuckoo'),
('hislic1', 'Hispaniolan Lizard-Cuckoo'),
('lesnig', 'Lesser Nighthawk'),
('comnig', 'Common Nighthawk'),
('antnig', 'Antillean Nighthawk'),
('shtnig1', 'Short-tailed Nighthawk'),
('compau', 'Common Pauraque'),
('sptnig1', 'Spot-tailed Nightjar'),
('whtnig1', 'White-tailed Nightjar'),
('leapau1', 'Least Pauraque'),
('earpoo1', 'Eared Poorwill'),
('yucpoo1', 'Yucatan Poorwill'),
('ocepoo1', 'Ocellated Poorwill'),
('compoo', 'Common Poorwill'),
('chwwid', 'Chuck-will''s-widow'),
('rufnig1', 'Rufous Nightjar'),
('granig2', 'Cuban Nightjar'),
('granig3', 'Hispaniolan Nightjar'),
('tacnig1', 'Tawny-collared Nightjar'),
('yucnig1', 'Yucatan Nightjar'),
('bucnig', 'Buff-collared Nightjar'),
('easwpw1', 'Eastern Whip-poor-will'),
('dusnig1', 'Dusky Nightjar'),
('souwpw1', 'Mexican Whip-poor-will'),
('purnig1', 'Puerto Rican Nightjar'),
('grepot1', 'Great Potoo'),
('compot1', 'Common Potoo'),
('norpot1', 'Northern Potoo'),
('blkswi', 'Black Swift'),
('whfswi1', 'White-fronted Swift'),
('whcswi1', 'White-chinned Swift'),
('spfswi1', 'Spot-fronted Swift'),
('chcswi1', 'Chestnut-collared Swift'),
('whcswi', 'White-collared Swift'),
('whnswi1', 'White-naped Swift'),
('grrswi1', 'Gray-rumped Swift'),
('barswi', 'Band-rumped Swift'),
('corswi', 'Costa Rican Swift'),
('leaswi1', 'Lesser Antillean Swift'),
('chiswi', 'Chimney Swift'),
('vauswi', 'Vaux''s Swift'),
('shtswi1', 'Short-tailed Swift'),
('marswi', 'Mariana Swiftlet'),
('whtswi', 'White-throated Swift'),
('lstswi1', 'Lesser Swallow-tailed Swift'),
('gstswi1', 'Great Swallow-tailed Swift'),
('anpswi', 'Antillean Palm Swift'),
('whnjac1', 'White-necked Jacobin'),
('whtsic1', 'White-tipped Sicklebill'),
('broher', 'Bronzy Hermit'),
('rubher', 'Rufous-breasted Hermit'),
('batbar1', 'Band-tailed Barbthroat'),
('greher1', 'Green Hermit'),
('lobher', 'Long-billed Hermit'),
('mexher1', 'Mexican Hermit'),
('pabher1', 'Pale-bellied Hermit'),
('stther2', 'Stripe-throated Hermit'),
('grflan1', 'Green-fronted Lancebill'),
('brvear1', 'Brown Violetear'),
('grnvie1', 'Mexican Violetear'),
('lesvio1', 'Lesser Violetear'),
('tobhum1', 'Tooth-billed Hummingbird'),
('pucfai1', 'Purple-crowned Fairy'),
('jamman1', 'Jamaican Mango'),
('bltman1', 'Black-throated Mango'),
('gnbman', 'Green-breasted Mango'),
('verman1', 'Veraguan Mango'),
('antman2', 'Hispaniolan Mango'),
('antman3', 'Puerto Rican Mango'),
('greman1', 'Green Mango'),
('putcar1', 'Purple-throated Carib'),
('grtcar1', 'Green-throated Carib'),
('gretho1', 'Green Thorntail'),
('shccoq', 'Short-crested Coquette'),
('ruccoq1', 'Rufous-crested Coquette'),
('blccoq1', 'Black-crested Coquette'),
('whccoq1', 'White-crested Coquette'),
('grepuf1', 'Greenish Puffleg'),
('grcbri1', 'Green-crowned Brilliant'),
('maghum1', 'Rivoli''s Hummingbird'),
('maghum2', 'Talamanca Hummingbird'),
('lobsta1', 'Long-billed Starthroat'),
('plcsta', 'Plain-capped Starthroat'),
('fithum1', 'Fiery-throated Hummingbird'),
('gtmgem1', 'Green-throated Mountain-gem'),
('gbmgem1', 'Green-breasted Mountain-gem'),
('amthum1', 'Amethyst-throated Mountain-gem'),
('buthum', 'Blue-throated Mountain-gem'),
('wbmgem1', 'White-bellied Mountain-gem'),
('ptmgem', 'Purple-throated Mountain-gem'),
('wtmgem1', 'White-throated Mountain-gem'),
('gathum1', 'Garnet-throated Hummingbird'),
('spthum1', 'Sparkling-tailed Hummingbird'),
('matwoo1', 'Magenta-throated Woodstar'),
('putwoo1', 'Purple-throated Woodstar'),
('sleshe1', 'Slender Sheartail'),
('mexshe1', 'Mexican Sheartail'),
('luchum', 'Lucifer Hummingbird'),
('beahum1', 'Beautiful Hummingbird'),
('rthhum', 'Ruby-throated Hummingbird'),
('bkchum', 'Black-chinned Hummingbird'),
('bahwoo', 'Bahama Woodstar'),
('inawoo2', 'Inagua Woodstar'),
('verhum1', 'Vervain Hummingbird'),
('beehum1', 'Bee Hummingbird'),
('annhum', 'Anna''s Hummingbird'),
('coshum', 'Costa''s Hummingbird'),
('calhum', 'Calliope Hummingbird'),
('rufhum', 'Rufous Hummingbird'),
('allhum', 'Allen''s Hummingbird'),
('brthum', 'Broad-tailed Hummingbird'),
('bumhum', 'Bumblebee Hummingbird'),
('withum1', 'Wine-throated Hummingbird'),
('volhum1', 'Volcano Hummingbird'),
('scihum1', 'Scintillant Hummingbird'),
('glthum1', 'Glow-throated Hummingbird'),
('dushum1', 'Dusky Hummingbird'),
('cubeme1', 'Cuban Emerald'),
('hiseme1', 'Hispaniolan Emerald'),
('pureme1', 'Puerto Rican Emerald'),
('blhhum1', 'Blue-headed Hummingbird'),
('brbhum', 'Broad-billed Hummingbird'),
('brbhum3', 'Tres Marias Hummingbird'),
('brbhum2', 'Turquoise-crowned Hummingbird'),
('goceme1', 'Golden-crowned Emerald'),
('cozeme1', 'Cozumel Emerald'),
('caneme1', 'Canivet''s Emerald'),
('gareme1', 'Garden Emerald'),
('whehum', 'White-eared Hummingbird'),
('xanhum', 'Xantus''s Hummingbird'),
('wetsab1', 'Wedge-tailed Sabrewing'),
('rufsab1', 'Rufous Sabrewing'),
('vihhum1', 'Violet-headed Hummingbird'),
('emchum1', 'Emerald-chinned Hummingbird'),
('anchum1', 'Antillean Crested Hummingbird'),
('viosab1', 'Violet Sabrewing'),
('brtplu1', 'Bronze-tailed Plumeleteer'),
('whvplu1', 'White-vented Plumeleteer'),
('crowoo1', 'Crowned Woodnymph'),
('snowca1', 'Snowcap'),
('coheme1', 'Coppery-headed Emerald'),
('whteme1', 'White-tailed Emerald'),
('vichum1', 'Violet-capped Hummingbird'),
('ruchum1', 'Pirre Hummingbird'),
('mexwoo1', 'Mexican Woodnymph'),
('whthum1', 'White-tailed Hummingbird'),
('blchum2', 'Blue-capped Hummingbird'),
('stthum1', 'Stripe-tailed Hummingbird'),
('blbhum1', 'Black-bellied Hummingbird'),
('scbhum1', 'Scaly-breasted Hummingbird'),
('stream2', 'Red-billed Streamertail'),
('stream3', 'Black-billed Streamertail'),
('vichum', 'Violet-crowned Hummingbird'),
('grfhum1', 'Green-fronted Hummingbird'),
('azchum1', 'Azure-crowned Hummingbird'),
('buvhum1', 'Blue-vented Hummingbird'),
('berhum', 'Berylline Hummingbird'),
('blthum1', 'Blue-tailed Hummingbird'),
('snbhum1', 'Snowy-bellied Hummingbird'),
('cinhum1', 'Cinnamon Hummingbird'),
('bubhum', 'Buff-bellied Hummingbird'),
('rtlhum', 'Rufous-tailed Hummingbird'),
('manhum1', 'Mangrove Hummingbird'),
('sathum1', 'Sapphire-throated Hummingbird'),
('humsap2', 'Humboldt''s Sapphire'),
('blchum1', 'Blue-chested Hummingbird'),
('chahum1', 'Charming Hummingbird'),
('whbeme1', 'White-bellied Emerald'),
('bltgol1', 'Blue-throated Goldentail'),
('vibhum1', 'Violet-bellied Hummingbird'),
('ridrai1', 'Ridgway''s Rail'),
('kinrai2', 'Aztec Rail'),
('manrai1', 'Mangrove Rail'),
('kinrai4', 'King Rail'),
('clarai11', 'Clapper Rail'),
('virrai', 'Virginia Rail'),
('sporai', 'Spotted Rail'),
('zaprai1', 'Zapata Rail'),
('colcra2', 'Colombian Crake'),
('pabcra', 'Paint-billed Crake'),
('unicra1', 'Uniform Crake'),
('rnwrai1', 'Rufous-necked Wood-Rail'),
('runwor1', 'Russet-naped Wood-Rail'),
('gycwor1', 'Gray-cowled Wood-Rail'),
('sora', 'Sora'),
('comgal1', 'Common Gallinule'),
('hawcoo', 'Hawaiian Coot'),
('y00475', 'American Coot'),
('purgal2', 'Purple Gallinule'),
('ocecra1', 'Ocellated Crake'),
('yelrai', 'Yellow Rail'),
('yebcra1', 'Yellow-breasted Crake'),
('rudcra1', 'Ruddy Crake'),
('whtcra1', 'White-throated Crake'),
('grbcra1', 'Gray-breasted Crake'),
('blkrai', 'Black Rail'),
('sungre1', 'Sungrebe'),
('limpki', 'Limpkin'),
('sancra', 'Sandhill Crane'),
('whocra', 'Whooping Crane'),
('dstkne', 'Double-striped Thick-knee'),
('bknsti', 'Black-necked Stilt'),
('ameavo', 'American Avocet'),
('ameoys', 'American Oystercatcher'),
('blkoys', 'Black Oystercatcher'),
('bkbplo', 'Black-bellied Plover'),
('eugplo', 'European Golden-Plover'),
('amgplo', 'American Golden-Plover'),
('pagplo', 'Pacific Golden-Plover'),
('eurdot', 'Eurasian Dotterel'),
('killde', 'Killdeer'),
('corplo', 'Common Ringed Plover'),
('semplo', 'Semipalmated Plover'),
('pipplo', 'Piping Plover'),
('soulap1', 'Southern Lapwing'),
('lessap2', 'Siberian Sand-Plover'),
('wilplo', 'Wilson''s Plover'),
('colplo1', 'Collared Plover'),
('mouplo', 'Mountain Plover'),
('snoplo5', 'Snowy Plover'),
('norjac', 'Northern Jacana'),
('watjac1', 'Wattled Jacana'),
('uplsan', 'Upland Sandpiper'),
('brtcur', 'Bristle-thighed Curlew'),
('whimbr3', 'Hudsonian Whimbrel'),
('whimbr5', 'Eurasian Whimbrel'),
('eskcur', 'Eskimo Curlew'),
('lobcur', 'Long-billed Curlew'),
('faecur', 'Far Eastern Curlew'),
('batgod', 'Bar-tailed Godwit'),
('bktgod', 'Black-tailed Godwit'),
('hudgod', 'Hudsonian Godwit'),
('margod', 'Marbled Godwit'),
('shbdow', 'Short-billed Dowitcher'),
('lobdow', 'Long-billed Dowitcher'),
('amewoo', 'American Woodcock'),
('comsni', 'Common Snipe'),
('wilsni1', 'Wilson''s Snipe'),
('wilpha', 'Wilson''s Phalarope'),
('redpha1', 'Red Phalarope'),
('renpha', 'Red-necked Phalarope'),
('tersan', 'Terek Sandpiper'),
('comsan', 'Common Sandpiper'),
('sposan', 'Spotted Sandpiper'),
('solsan', 'Solitary Sandpiper'),
('gyttat1', 'Gray-tailed Tattler'),
('wantat1', 'Wandering Tattler'),
('woosan', 'Wood Sandpiper'),
('lesyel', 'Lesser Yellowlegs'),
('willet1', 'Willet'),
('spored', 'Spotted Redshank'),
('comgre', 'Common Greenshank'),
('greyel', 'Greater Yellowlegs'),
('rudtur', 'Ruddy Turnstone'),
('blktur', 'Black Turnstone'),
('redkno', 'Red Knot'),
('surfbi', 'Surfbird'),
('ruff', 'Ruff'),
('shtsan', 'Sharp-tailed Sandpiper'),
('cursan', 'Curlew Sandpiper'),
('stisan', 'Stilt Sandpiper'),
('lotsti', 'Long-toed Stint'),
('rensti', 'Red-necked Stint'),
('bubsan', 'Buff-breasted Sandpiper'),
('sander', 'Sanderling'),
('dunlin', 'Dunlin'),
('pursan', 'Purple Sandpiper'),
('rocsan', 'Rock Sandpiper'),
('baisan', 'Baird''s Sandpiper'),
('litsti', 'Little Stint'),
('whrsan', 'White-rumped Sandpiper'),
('leasan', 'Least Sandpiper'),
('pecsan', 'Pectoral Sandpiper'),
('wessan', 'Western Sandpiper'),
('semsan', 'Semipalmated Sandpiper'),
('lotjae', 'Long-tailed Jaeger'),
('parjae', 'Parasitic Jaeger'),
('pomjae', 'Pomarine Jaeger'),
('gresku1', 'Great Skua'),
('sopsku1', 'South Polar Skua'),
('rhiauk', 'Rhinoceros Auklet'),
('tufpuf', 'Tufted Puffin'),
('atlpuf', 'Atlantic Puffin'),
('horpuf', 'Horned Puffin'),
('casauk', 'Cassin''s Auklet'),
('leaauk', 'Least Auklet'),
('whiauk', 'Whiskered Auklet'),
('creauk', 'Crested Auklet'),
('parauk', 'Parakeet Auklet'),
('kitmur', 'Kittlitz''s Murrelet'),
('marmur', 'Marbled Murrelet'),
('blkgui', 'Black Guillemot'),
('piggui', 'Pigeon Guillemot'),
('razorb', 'Razorbill'),
('doveki', 'Dovekie'),
('thbmur', 'Thick-billed Murre'),
('commur', 'Common Murre'),
('ancmur', 'Ancient Murrelet'),
('xanmur2', 'Scripps''s Murrelet'),
('xanmur1', 'Guadalupe Murrelet'),
('cramur', 'Craveri''s Murrelet'),
('litgul', 'Little Gull'),
('rosgul', 'Ross''s Gull'),
('bklkit', 'Black-legged Kittiwake'),
('relkit', 'Red-legged Kittiwake'),
('ivogul', 'Ivory Gull'),
('sabgul', 'Sabine''s Gull'),
('bongul', 'Bonaparte''s Gull'),
('bkhgul', 'Black-headed Gull'),
('laugul', 'Laughing Gull'),
('fragul', 'Franklin''s Gull'),
('heegul', 'Heermann''s Gull'),
('mewgul', 'Common Gull'),
('mewgul2', 'Short-billed Gull'),
('ribgul', 'Ring-billed Gull'),
('yefgul', 'Yellow-footed Gull'),
('wesgul', 'Western Gull'),
('kelgul', 'Kelp Gull'),
('amhgul1', 'American Herring Gull'),
('veggul1', 'Vega Gull'),
('gbbgul', 'Great Black-backed Gull'),
('glagul', 'Glaucous Gull'),
('lbbgul', 'Lesser Black-backed Gull'),
('calgul', 'California Gull'),
('glwgul', 'Glaucous-winged Gull'),
('slbgul', 'Slaty-backed Gull'),
('y00478', 'Iceland Gull'),
('blkski', 'Black Skimmer'),
('whiter4', 'Blue-billed White-Tern'),
('brnnod', 'Brown Noddy'),
('blknod', 'Black Noddy'),
('bugnod', 'Blue-gray Noddy'),
('aleter1', 'Aleutian Tern'),
('sooter1', 'Sooty Tern'),
('briter1', 'Bridled Tern'),
('leater1', 'Least Tern'),
('gubter2', 'Gull-billed Tern'),
('caster1', 'Caspian Tern'),
('blkter', 'Black Tern'),
('forter', 'Forster''s Tern'),
('arcter', 'Arctic Tern'),
('comter', 'Common Tern'),
('roster', 'Roseate Tern'),
('santer1', 'Sandwich Tern'),
('eleter1', 'Elegant Tern'),
('royter1', 'Royal Tern'),
('grefla2', 'American Flamingo'),
('leagre', 'Least Grebe'),
('pibgre', 'Pied-billed Grebe'),
('horgre', 'Horned Grebe'),
('rengre', 'Red-necked Grebe'),
('eargre', 'Eared Grebe'),
('wesgre', 'Western Grebe'),
('clagre', 'Clark''s Grebe'),
('sunbit1', 'Sunbittern'),
('whttro', 'White-tailed Tropicbird'),
('rebtro', 'Red-billed Tropicbird'),
('rettro', 'Red-tailed Tropicbird'),
('retloo', 'Red-throated Loon'),
('arcloo', 'Arctic Loon'),
('pacloo', 'Pacific Loon'),
('comloo', 'Common Loon'),
('yebloo', 'Yellow-billed Loon'),
('layalb', 'Laysan Albatross'),
('bkfalb', 'Black-footed Albatross'),
('shtalb', 'Short-tailed Albatross'),
('wispet', 'Wilson''s Storm-Petrel'),
('wfspet', 'White-faced Storm-Petrel'),
('ftspet', 'Fork-tailed Storm-Petrel'),
('lcspet', 'Leach''s Storm-Petrel'),
('leastp5', 'Townsend''s Storm-Petrel'),
('leastp2', 'Ainley''s Storm-Petrel'),
('asspet', 'Ashy Storm-Petrel'),
('barpet', 'Band-rumped Storm-Petrel'),
('wrspet', 'Wedge-rumped Storm-Petrel'),
('bkspet', 'Black Storm-Petrel'),
('trspet', 'Tristram''s Storm-Petrel'),
('lsspet', 'Least Storm-Petrel'),
('norful', 'Northern Fulmar'),
('tripet1', 'Trindade Petrel'),
('murpet', 'Murphy''s Petrel'),
('feapet3', 'Cape Verde Petrel'),
('motpet', 'Mottled Petrel'),
('berpet', 'Bermuda Petrel'),
('bkcpet', 'Black-capped Petrel'),
('bkcpet2', 'Jamaican Petrel'),
('jufpet', 'Juan Fernandez Petrel'),
('galpet', 'Galapagos Petrel'),
('hawpet1', 'Hawaiian Petrel'),
('whnpet', 'White-necked Petrel'),
('bonpet', 'Bonin Petrel'),
('coopet', 'Cook''s Petrel'),
('bulpet', 'Bulwer''s Petrel'),
('parpet1', 'Parkinson''s Petrel'),
('corshe1', 'Cory''s Shearwater'),
('scoshe1', 'Scopoli''s Shearwater'),
('pifshe', 'Pink-footed Shearwater'),
('flfshe', 'Flesh-footed Shearwater'),
('greshe', 'Great Shearwater'),
('wetshe', 'Wedge-tailed Shearwater'),
('bulshe', 'Buller''s Shearwater'),
('sooshe', 'Sooty Shearwater'),
('shtshe', 'Short-tailed Shearwater'),
('chrshe', 'Christmas Shearwater'),
('audshe3', 'Galapagos Shearwater'),
('manshe', 'Manx Shearwater'),
('towshe1', 'Townsend''s Shearwater'),
('towshe2', 'Newell''s Shearwater'),
('bkvshe', 'Black-vented Shearwater'),
('audshe', 'Sargasso Shearwater'),
('jabiru', 'Jabiru'),
('woosto', 'Wood Stork'),
('magfri', 'Magnificent Frigatebird'),
('grefri', 'Great Frigatebird'),
('norgan', 'Northern Gannet'),
('refboo', 'Red-footed Booby'),
('brnboo', 'Brown Booby'),
('cocboo1', 'Cocos Booby'),
('masboo', 'Masked Booby'),
('nazboo1', 'Nazca Booby'),
('bfoboo', 'Blue-footed Booby'),
('anhing', 'Anhinga'),
('bracor', 'Brandt''s Cormorant'),
('refcor', 'Red-faced Cormorant'),
('pelcor', 'Pelagic Cormorant'),
('grecor', 'Great Cormorant'),
('doccor', 'Double-crested Cormorant'),
('neocor', 'Neotropic Cormorant'),
('whiibi', 'White Ibis'),
('gloibi', 'Glossy Ibis'),
('whfibi', 'White-faced Ibis'),
('greibi1', 'Green Ibis'),
('rosspo1', 'Roseate Spoonbill'),
('ruther1', 'Rufescent Tiger-Heron'),
('btther1', 'Bare-throated Tiger-Heron'),
('father1', 'Fasciated Tiger-Heron'),
('bobher1', 'Boat-billed Heron'),
('agaher1', 'Agami Heron'),
('amebit', 'American Bittern'),
('pinbit1', 'Pinnated Bittern'),
('leabit', 'Least Bittern'),
('ycnher', 'Yellow-crowned Night Heron'),
('bcnher', 'Black-crowned Night Heron'),
('capher1', 'Capped Heron'),
('libher', 'Little Blue Heron'),
('triher', 'Tricolored Heron'),
('redegr', 'Reddish Egret'),
('snoegr', 'Snowy Egret'),
('litegr', 'Little Egret'),
('strher2', 'Striated Heron'),
('grnher', 'Green Heron'),
('categr1', 'Western Cattle-Egret'),
('greegr', 'Great Egret'),
('grbher3', 'Great Blue Heron'),
('cocher1', 'Cocoi Heron'),
('amwpel', 'American White Pelican'),
('brnpel', 'Brown Pelican'),
('calcon', 'California Condor'),
('kinvul1', 'King Vulture'),
('blkvul', 'Black Vulture'),
('turvul', 'Turkey Vulture'),
('lyhvul1', 'Lesser Yellow-headed Vulture'),
('osprey', 'Osprey'),
('peakit1', 'Pearl Kite'),
('whtkit', 'White-tailed Kite'),
('hobkit', 'Hook-billed Kite'),
('hobkit2', 'Cuban Kite'),
('grhkit1', 'Gray-headed Kite'),
('swtkit', 'Swallow-tailed Kite'),
('blheag1', 'Black Hawk-Eagle'),
('bawhae1', 'Black-and-white Hawk-Eagle'),
('orheag1', 'Ornate Hawk-Eagle'),
('goleag', 'Golden Eagle'),
('creeag1', 'Crested Eagle'),
('hareag1', 'Harpy Eagle'),
('shshaw', 'Sharp-shinned Hawk'),
('bichaw1', 'Bicolored Hawk'),
('coohaw', 'Cooper''s Hawk'),
('gunhaw1', 'Gundlach''s Hawk'),
('norgos', 'American Goshawk'),
('norhar2', 'Northern Harrier'),
('tinhaw1', 'Tiny Hawk'),
('dotkit1', 'Double-toothed Kite'),
('whteag', 'White-tailed Eagle'),
('baleag', 'Bald Eagle'),
('miskit', 'Mississippi Kite'),
('plukit1', 'Plumbeous Kite'),
('crahaw', 'Crane Hawk'),
('blchaw1', 'Black-collared Hawk'),
('snakit', 'Snail Kite'),
('slbkit1', 'Slender-billed Kite'),
('barhaw1', 'Barred Hawk'),
('pluhaw', 'Plumbeous Hawk'),
('comblh1', 'Common Black Hawk'),
('cubblh1', 'Cuban Black Hawk'),
('savhaw1', 'Savanna Hawk'),
('grbhaw1', 'Great Black Hawk'),
('soleag1', 'Solitary Eagle'),
('roahaw', 'Roadside Hawk'),
('hrshaw', 'Harris''s Hawk'),
('whthaw', 'White-tailed Hawk'),
('whihaw1', 'White Hawk'),
('semhaw', 'Semiplumbeous Hawk'),
('gryhaw2', 'Gray Hawk'),
('gryhaw3', 'Gray-lined Hawk'),
('brwhaw', 'Broad-winged Hawk'),
('reshaw', 'Red-shouldered Hawk'),
('ridhaw1', 'Ridgway''s Hawk'),
('zothaw', 'Zone-tailed Hawk'),
('hawhaw', 'Hawaiian Hawk'),
('shthaw', 'Short-tailed Hawk'),
('swahaw', 'Swainson''s Hawk'),
('rethaw', 'Red-tailed Hawk'),
('rolhaw', 'Rough-legged Hawk'),
('ferhaw', 'Ferruginous Hawk'),
('brnowl', 'American Barn Owl'),
('asfowl1', 'Ashy-faced Owl'),
('flaowl', 'Flammulated Owl'),
('prsowl', 'Puerto Rican Owl'),
('bssowl', 'Bare-shanked Screech-Owl'),
('whsowl1', 'Whiskered Screech-Owl'),
('trsowl', 'Tropical Screech-Owl'),
('vesowl', 'Middle American Screech-Owl'),
('versco2', 'Choco Screech-Owl'),
('besowl', 'Bearded Screech-Owl'),
('basowl', 'Balsas Screech-Owl'),
('pasowl4', 'Pacific Screech-Owl'),
('wesowl1', 'Western Screech-Owl'),
('easowl1', 'Eastern Screech-Owl'),
('balowl', 'Bare-legged Owl'),
('creowl1', 'Crested Owl'),
('speowl1', 'Spectacled Owl'),
('snoowl1', 'Snowy Owl'),
('grhowl', 'Great Horned Owl'),
('nohowl', 'Northern Hawk Owl'),
('nopowl', 'Northern Pygmy-Owl'),
('crpowl', 'Costa Rican Pygmy-Owl'),
('capowl1', 'Central American Pygmy-Owl'),
('tapowl1', 'Tamaulipas Pygmy-Owl'),
('copowl1', 'Colima Pygmy-Owl'),
('fepowl', 'Ferruginous Pygmy-Owl'),
('cupowl1', 'Cuban Pygmy-Owl'),
('elfowl', 'Elf Owl'),
('burowl', 'Burrowing Owl'),
('motowl', 'Mottled Owl'),
('bawowl1', 'Black-and-white Owl'),
('spoowl', 'Spotted Owl'),
('brdowl', 'Barred Owl'),
('barowl13', 'Cinereous Owl'),
('fulowl1', 'Fulvous Owl'),
('grgowl', 'Great Gray Owl'),
('jamowl1', 'Jamaican Owl'),
('loeowl', 'Long-eared Owl'),
('strowl1', 'Striped Owl'),
('styowl1', 'Stygian Owl'),
('sheowl', 'Short-eared Owl'),
('borowl', 'Boreal Owl'),
('nswowl', 'Northern Saw-whet Owl'),
('uswowl1', 'Unspotted Saw-whet Owl'),
('earque', 'Eared Quetzal'),
('gohque1', 'Golden-headed Quetzal'),
('resque1', 'Resplendent Quetzal'),
('cubtro1', 'Cuban Trogon'),
('histro1', 'Hispaniolan Trogon'),
('lattro1', 'Lattice-tailed Trogon'),
('slttro1', 'Slaty-tailed Trogon'),
('blttro1', 'Black-tailed Trogon'),
('blhtro1', 'Black-headed Trogon'),
('cittro1', 'Citreoline Trogon'),
('whttro1', 'White-tailed Trogon'),
('baitro1', 'Baird''s Trogon'),
('gartro1', 'Gartered Violaceous Trogon'),
('bkttro7', 'Graceful Black-throated Trogon'),
('eletro2', 'Elegant Trogon'),
('moutro1', 'Mountain Trogon'),
('coltro1', 'Collared Trogon'),
('cubtod1', 'Cuban Tody'),
('brbtod1', 'Broad-billed Tody'),
('nabtod1', 'Narrow-billed Tody'),
('jamtod1', 'Jamaican Tody'),
('purtod1', 'Puerto Rican Tody'),
('todmot1', 'Tody Motmot'),
('bltmot1', 'Blue-throated Motmot'),
('rucmot1', 'Russet-crowned Motmot'),
('bucmot1', 'Blue-capped Motmot'),
('bucmot2', 'Lesson''s Motmot'),
('bucmot3', 'Whooping Motmot'),
('rufmot1', 'Rufous Motmot'),
('kebmot1', 'Keel-billed Motmot'),
('brbmot1', 'Broad-billed Motmot'),
('tubmot1', 'Turquoise-browed Motmot'),
('rinkin1', 'Ringed Kingfisher'),
('belkin1', 'Belted Kingfisher'),
('amakin1', 'Amazon Kingfisher'),
('ampkin1', 'American Pygmy Kingfisher'),
('grnkin', 'Green Kingfisher'),
('garkin1', 'Green-and-rufous Kingfisher'),
('whnpuf2', 'White-necked Puffbird'),
('blbpuf1', 'Black-breasted Puffbird'),
('piepuf1', 'Pied Puffbird'),
('barpuf1', 'Barred Puffbird'),
('whwpuf1', 'White-whiskered Puffbird'),
('lanmon1', 'Lanceolated Monklet'),
('gycnun1', 'Gray-cheeked Nunlet'),
('whfnun1', 'White-fronted Nunbird'),
('dubjac1', 'Dusky-backed Jacamar'),
('rutjac1', 'Rufous-tailed Jacamar'),
('grejac2', 'Great Jacamar'),
('spcbar1', 'Spot-crowned Barbet'),
('rehbar1', 'Red-headed Barbet'),
('prbbar1', 'Prong-billed Barbet'),
('noremt1', 'Northern Emerald-Toucanet'),
('colara2', 'Collared Aracari'),
('fibara1', 'Fiery-billed Aracari'),
('yeetou1', 'Yellow-eared Toucanet'),
('bkmtou1', 'Yellow-throated Toucan'),
('kebtou1', 'Keel-billed Toucan'),
('olipic1', 'Olivaceous Piculet'),
('antpic1', 'Antillean Piculet'),
('wilsap', 'Williamson''s Sapsucker'),
('yebsap', 'Yellow-bellied Sapsucker'),
('rensap', 'Red-naped Sapsucker'),
('rebsap', 'Red-breasted Sapsucker'),
('cugwoo1', 'Cuban Green Woodpecker'),
('lewwoo', 'Lewis''s Woodpecker'),
('guawoo1', 'Guadeloupe Woodpecker'),
('purwoo1', 'Puerto Rican Woodpecker'),
('rehwoo', 'Red-headed Woodpecker'),
('acowoo', 'Acorn Woodpecker'),
('gonwoo1', 'Golden-naped Woodpecker'),
('blcwoo1', 'Black-cheeked Woodpecker'),
('hiswoo1', 'Hispaniolan Woodpecker'),
('jamwoo1', 'Jamaican Woodpecker'),
('gocwoo1', 'Golden-cheeked Woodpecker'),
('grbwoo1', 'Gray-breasted Woodpecker'),
('yucwoo', 'Yucatan Woodpecker'),
('recwoo1', 'Red-crowned Woodpecker'),
('gilwoo', 'Gila Woodpecker'),
('hofwoo1', 'Hoffmann''s Woodpecker'),
('gofwoo', 'Golden-fronted Woodpecker'),
('rebwoo', 'Red-bellied Woodpecker'),
('weiwoo1', 'West Indian Woodpecker'),
('attwoo1', 'American Three-toed Woodpecker'),
('bkbwoo', 'Black-backed Woodpecker'),
('dowwoo', 'Downy Woodpecker'),
('nutwoo', 'Nuttall''s Woodpecker'),
('labwoo', 'Ladder-backed Woodpecker'),
('recwoo', 'Red-cockaded Woodpecker'),
('haiwoo', 'Hairy Woodpecker'),
('whhwoo', 'White-headed Woodpecker'),
('smbwoo1', 'Smoky-brown Woodpecker'),
('strwoo', 'Strickland''s Woodpecker'),
('ariwoo', 'Arizona Woodpecker'),
('rerwoo1', 'Red-rumped Woodpecker'),
('crbwoo1', 'Crimson-bellied Woodpecker'),
('crcwoo1', 'Crimson-crested Woodpecker'),
('pabwoo1', 'Pale-billed Woodpecker'),
('ivbwoo', 'Ivory-billed Woodpecker'),
('impwoo1', 'Imperial Woodpecker'),
('linwoo1', 'Lineated Woodpecker'),
('pilwoo', 'Pileated Woodpecker'),
('cinwoo1', 'Cinnamon Woodpecker'),
('chcwoo1', 'Chestnut-colored Woodpecker'),
('ruwwoo1', 'Rufous-winged Woodpecker'),
('stcwoo1', 'Stripe-cheeked Woodpecker'),
('gogwoo1', 'Golden-green Woodpecker'),
('goowoo1', 'Golden-olive Woodpecker'),
('grcwoo1', 'Gray-crowned Woodpecker'),
('spbwoo1', 'Spot-breasted Woodpecker'),
('norfli', 'Northern Flicker'),
('norfli1', 'Guatemalan Flicker'),
('gilfli', 'Gilded Flicker'),
('ferfli1', 'Fernandina''s Flicker'),
('laufal1', 'Laughing Falcon'),
('coffal1', 'Collared Forest-Falcon'),
('sbffal1', 'Slaty-backed Forest-Falcon'),
('baffal1', 'Barred Forest-Falcon'),
('y00678', 'Crested Caracara'),
('retcar2', 'Red-throated Caracara'),
('yehcar1', 'Yellow-headed Caracara'),
('amekes', 'American Kestrel'),
('merlin', 'Merlin'),
('aplfal', 'Aplomado Falcon'),
('batfal1', 'Bat Falcon'),
('orbfal1', 'Orange-breasted Falcon'),
('gyrfal', 'Gyrfalcon'),
('perfal', 'Peregrine Falcon'),
('prafal', 'Prairie Falcon'),
('rorpar', 'Rose-ringed Parakeet'),
('peflov', 'Rosy-faced Lovebird'),
('refpar1', 'Red-fronted Parrotlet'),
('bufpar1', 'Blue-fronted Parrotlet'),
('barpar1', 'Barred Parakeet'),
('monpar', 'Monk Parakeet'),
('whwpar', 'White-winged Parakeet'),
('yecpar', 'Yellow-chevroned Parakeet'),
('orcpar', 'Orange-chinned Parakeet'),
('brhpar1', 'Brown-hooded Parrot'),
('sahpar1', 'Saffron-headed Parrot'),
('blhpar1', 'Blue-headed Parrot'),
('whcpar', 'White-crowned Parrot'),
('recpar', 'Red-crowned Amazon'),
('licpar', 'Lilac-crowned Amazon'),
('relpar10', 'Red-lored Amazon'),
('renpar1', 'Red-necked Amazon'),
('stlpar1', 'St. Lucia Amazon'),
('yenpar1', 'Yellow-naped Amazon'),
('yehpar', 'Yellow-headed Amazon'),
('ywcpar', 'Yellow-crowned Amazon'),
('blbpar1', 'Black-billed Amazon'),
('whfpar1', 'White-fronted Amazon'),
('yelpar1', 'Yellow-lored Amazon'),
('yebpar1', 'Yellow-billed Amazon'),
('cubpar1', 'Cuban Amazon'),
('hispar1', 'Hispaniolan Amazon'),
('purpar1', 'Puerto Rican Amazon'),
('meapar', 'Mealy Amazon'),
('imppar1', 'Imperial Amazon'),
('stvpar1', 'St. Vincent Amazon'),
('mexpar1', 'Mexican Parrotlet'),
('grrpar1', 'Green-rumped Parrotlet'),
('spepar1', 'Spectacled Parrotlet'),
('paipar2', 'Painted Parakeet'),
('suwpar1', 'Sulphur-winged Parakeet'),
('thbpar', 'Thick-billed Parrot'),
('mafpar1', 'Maroon-fronted Parrot'),
('oltpar1', 'Olive-throated Parakeet'),
('orfpar', 'Orange-fronted Parakeet'),
('brtpar1', 'Brown-throated Parakeet'),
('bkhpar', 'Nanday Parakeet'),
('baymac', 'Blue-and-yellow Macaw'),
('chfmac1', 'Chestnut-fronted Macaw'),
('milmac', 'Military Macaw'),
('grgmac', 'Great Green Macaw'),
('scamac1', 'Scarlet Macaw'),
('ragmac1', 'Red-and-green Macaw'),
('grnpar', 'Green Parakeet'),
('grnpar2', 'Socorro Parakeet'),
('pacpar1', 'Pacific Parakeet'),
('crfpar', 'Crimson-fronted Parakeet'),
('mitpar', 'Mitred Parakeet'),
('rempar', 'Red-masked Parakeet'),
('cubpar2', 'Cuban Parakeet'),
('hispar', 'Hispaniolan Parakeet'),
('sapayo1', 'Sapayoa'),
('rurant1', 'Rufous-rumped Antwren'),
('fasant1', 'Fasciated Antshrike'),
('greant1', 'Great Antshrike'),
('barant1', 'Barred Antshrike'),
('wesant1', 'Black-crowned Antshrike'),
('blhant2', 'Black-hooded Antshrike'),
('blaant1', 'Black Antshrike'),
('rusant1', 'Russet Antshrike'),
('plaant1', 'Plain Antvireo'),
('stcant1', 'Streak-crowned Antvireo'),
('spcant1', 'Spot-crowned Antvireo'),
('spfant1', 'Spiny-faced Antshrike'),
('chtant1', 'Checker-throated Stipplethroat'),
('mouant', 'Moustached Antwren'),
('pacant', 'Pacific Antwren'),
('whfant2', 'White-flanked Antwren'),
('slaant1', 'Slaty Antwren'),
('ruwant3', 'Rusty-winged Antwren'),
('dowant1', 'Dot-winged Antwren'),
('whfant4', 'Northern White-fringed Antwren'),
('whfant3', 'Southern White-fringed Antwren'),
('dusant1', 'Dusky Antbird'),
('jetant1', 'Jet Antbird'),
('bacant1', 'Bare-crowned Antbird'),
('whbant1', 'White-bellied Antbird'),
('chbant1', 'Chestnut-backed Antbird'),
('dumant1', 'Dull-mantled Antbird'),
('zelant1', 'Zeledon''s Antbird'),
('wibant1', 'Wing-banded Antbird'),
('bicant2', 'Bicolored Antbird'),
('spoant1', 'Spotted Antbird'),
('oceant1', 'Ocellated Antbird'),
('blcant1', 'Black-crowned Antpitta'),
('scaant1', 'Scaled Antpitta'),
('stcant2', 'Streak-chested Antpitta'),
('thiant1', 'Thicket Antpitta'),
('ocbant1', 'Ochre-breasted Antpitta'),
('siftap1', 'Silvery-fronted Tapaculo'),
('tactap1', 'Tacarcuna Tapaculo'),
('chotap1', 'Choco Tapaculo'),
('bkfant2', 'Mayan Antthrush'),
('blfant1', 'Black-faced Antthrush'),
('bkhant7', 'Black-capped Antthrush'),
('rubant1', 'Rufous-breasted Antthrush'),
('tatlea1', 'Middle American Leaftosser'),
('sctlea1', 'Scaly-throated Leaftosser'),
('grtlea1', 'Gray-throated Leaftosser'),
('oliwoo1', 'Olivaceous Woodcreeper'),
('lotwoo3', 'Piping Long-tailed Woodcreeper'),
('lotwoo4', 'Whistling Long-tailed Woodcreeper'),
('lotwoo5', 'Mournful Long-tailed Woodcreeper'),
('rudwoo1', 'Ruddy Woodcreeper'),
('tawwoo1', 'Tawny-winged Woodcreeper'),
('plbwoo1', 'Plain-brown Woodcreeper'),
('webwoo1', 'Wedge-billed Woodcreeper'),
('nobwoo1', 'Northern Barred-Woodcreeper'),
('blbwoo1', 'Black-banded Woodcreeper'),
('stbwoo1', 'Strong-billed Woodcreeper'),
('cocwoo1', 'Cocoa Woodcreeper'),
('ivbwoo1', 'Ivory-billed Woodcreeper'),
('blswoo1', 'Black-striped Woodcreeper'),
('spowoo1', 'Spotted Woodcreeper'),
('stbwoo2', 'Straight-billed Woodcreeper'),
('rebscy1', 'Red-billed Scythebill'),
('brbscy1', 'Brown-billed Scythebill'),
('sthwoo1', 'Streak-headed Woodcreeper'),
('whswoo1', 'White-striped Woodcreeper'),
('spcwoo1', 'Spot-crowned Woodcreeper'),
('plaxen2', 'Northern Plain-Xenops'),
('strxen1', 'Streaked Xenops'),
('buftuf1', 'Buffy Tuftedcheek'),
('shtstr1', 'Sharp-tailed Streamcreeper'),
('swfgle', 'Slaty-winged Foliage-gleaner'),
('stfgle1', 'Scaly-throated Foliage-gleaner'),
('lifgle1', 'Lineated Foliage-gleaner'),
('bffgle', 'Buff-fronted Foliage-gleaner'),
('rufgle1', 'Ruddy Foliage-gleaner'),
('stbtre1', 'Streak-breasted Treehunter'),
('butfog9', 'Fawn-throated Foliage-gleaner'),
('butfog4', 'Chiriqui Foliage-gleaner'),
('btfgle1', 'Ochre-throated Foliage-gleaner'),
('strwoo4', 'Eastern Woodhaunter'),
('spobar1', 'Spotted Barbtail'),
('beatre1', 'Beautiful Treerunner'),
('rudtre1', 'Ruddy Treerunner'),
('dobgra1', 'Double-banded Graytail'),
('rubspi5', 'Coiba Spinetail'),
('refspi1', 'Red-faced Spinetail'),
('slaspi1', 'Slaty Spinetail'),
('pabspi1', 'Pale-breasted Spinetail'),
('rubspi2', 'Rufous-breasted Spinetail'),
('latman1', 'Lance-tailed Manakin'),
('lotman1', 'Long-tailed Manakin'),
('whrman1', 'White-ruffed Manakin'),
('greman2', 'Green Manakin'),
('bucman1', 'Velvety Manakin'),
('whcman1', 'White-collared Manakin'),
('orcman1', 'Orange-collared Manakin'),
('gocman1', 'Golden-collared Manakin'),
('whcman2', 'White-crowned Manakin'),
('recman1', 'Red-capped Manakin'),
('gohman1', 'Golden-headed Manakin'),
('putfru1', 'Purple-throated Fruitcrow'),
('banumb1', 'Bare-necked Umbrellabird'),
('lovcot1', 'Lovely Cotinga'),
('turcot1', 'Turquoise Cotinga'),
('blucot1', 'Blue Cotinga'),
('rufpih1', 'Rufous Piha'),
('thwbel', 'Three-wattled Bellbird'),
('bltcot1', 'Black-tipped Cotinga'),
('yebcot1', 'Yellow-billed Cotinga'),
('snocot1', 'Snowy Cotinga'),
('blctit1', 'Black-crowned Tityra'),
('mastit1', 'Masked Tityra'),
('thlsch2', 'Northern Schiffornis'),
('thlsch4', 'Russet-winged Schiffornis'),
('spemou1', 'Speckled Mourner'),
('barbec1', 'Barred Becard'),
('cinbec2', 'Cinereous Becard'),
('cinbec1', 'Cinnamon Becard'),
('whwbec1', 'White-winged Becard'),
('bawbec7', 'Black-and-white Becard'),
('grcbec1', 'Gray-collared Becard'),
('rotbec', 'Rose-throated Becard'),
('jambec1', 'Jamaican Becard'),
('oncbec1', 'One-colored Becard'),
('sharpb1', 'Sharpbill'),
('royfly1', 'Tropical Royal Flycatcher'),
('rutfly2', 'Ruddy-tailed Flycatcher'),
('tabfly1', 'Tawny-breasted Flycatcher'),
('surfly1', 'Sulphur-rumped Flycatcher'),
('bltfly1', 'Black-tailed Flycatcher'),
('grhpip1', 'Gray-headed Piprites'),
('sttspa1', 'Stub-tailed Spadebill'),
('whtspa1', 'White-throated Spadebill'),
('gocspa1', 'Golden-crowned Spadebill'),
('olsfly2', 'Olive-streaked Flycatcher'),
('ocbfly1', 'Ochre-bellied Flycatcher'),
('secfly1', 'Sepia-capped Flycatcher'),
('slcfly1', 'Slaty-capped Flycatcher'),
('yegtyr1', 'Yellow-green Tyrannulet'),
('rubtyr1', 'Rufous-browed Tyrannulet'),
('boptyr1', 'Bronze-olive Pygmy-Tyrant'),
('bcptyr1', 'Black-capped Pygmy-Tyrant'),
('scptyr1', 'Scale-crested Pygmy-Tyrant'),
('peptyr1', 'Pale-eyed Pygmy-Tyrant'),
('norben1', 'Northern Bentbill'),
('souben1', 'Southern Bentbill'),
('shtfly1', 'Slate-headed Tody-Flycatcher'),
('cotfly1', 'Common Tody-Flycatcher'),
('bhtfly1', 'Black-headed Tody-Flycatcher'),
('brofly1', 'Brownish Twistwing'),
('eyrfla1', 'Eye-ringed Flatbill'),
('olifla2', 'Western Olivaceous Flatbill'),
('olifla3', 'Eastern Olivaceous Flatbill'),
('yeofly1', 'Yellow-olive Flatbill'),
('yemfly2', 'Yellow-winged Flatbill'),
('yebfly3', 'Ochre-lored Flatbill'),
('yebtyr1', 'Yellow-bellied Tyrannulet'),
('brctyr', 'Brown-capped Tyrannulet'),
('nobtyr', 'Northern Beardless-Tyrannulet'),
('sobtyr1', 'Southern Beardless-Tyrannulet'),
('cocfly1', 'Cocos Tyrannulet'),
('y01204', 'Mouse-colored Tyrannulet'),
('yeltyr1', 'Yellow Tyrannulet'),
('yectyr1', 'Yellow-crowned Tyrannulet'),
('forela1', 'Forest Elaenia'),
('gryela3', 'Gray-headed Elaenia'),
('jamela1', 'Jamaican Elaenia'),
('greela', 'Greenish Elaenia'),
('yebela1', 'Yellow-bellied Elaenia'),
('lesela1', 'Lesser Elaenia'),
('mouela1', 'Mountain Elaenia'),
('carela1', 'Caribbean Elaenia'),
('graela3', 'Blue Mountain Elaenia'),
('tortyr1', 'Torrent Tyrannulet'),
('sohtyr1', 'Sooty-headed Tyrannulet'),
('roltyr1', 'White-fronted Tyrannulet'),
('paltyr2', 'Guatemalan Tyrannulet'),
('paltyr3', 'Mistletoe Tyrannulet'),
('brcfly1', 'Bran-colored Flycatcher'),
('eulfly1', 'Euler''s Flycatcher'),
('tacfly1', 'Tawny-chested Flycatcher'),
('blbfly1', 'Black-billed Flycatcher'),
('belfly1', 'Belted Flycatcher'),
('pilfly1', 'Pileated Flycatcher'),
('tuffly', 'Tufted Flycatcher'),
('olsfly', 'Olive-sided Flycatcher'),
('ochpew1', 'Ochraceous Pewee'),
('grepew', 'Greater Pewee'),
('darpew1', 'Dark Pewee'),
('jampew1', 'Jamaican Pewee'),
('tropew3', 'Southern Tropical Pewee'),
('wewpew', 'Western Wood-Pewee'),
('tropew4', 'Northern Tropical Pewee'),
('eawpew', 'Eastern Wood-Pewee'),
('cubpew1', 'Cuban Pewee'),
('hispew1', 'Hispaniolan Pewee'),
('leapew1', 'Lesser Antillean Pewee'),
('yebfly', 'Yellow-bellied Flycatcher'),
('acafly', 'Acadian Flycatcher'),
('aldfly', 'Alder Flycatcher'),
('wilfly', 'Willow Flycatcher'),
('whtfly1', 'White-throated Flycatcher'),
('leafly', 'Least Flycatcher'),
('hamfly', 'Hammond''s Flycatcher'),
('gryfly', 'Gray Flycatcher'),
('dusfly', 'Dusky Flycatcher'),
('pinfly1', 'Pine Flycatcher'),
('wesfly', 'Western Flycatcher'),
('yelfly1', 'Yellowish Flycatcher'),
('bubfly', 'Buff-breasted Flycatcher'),
('blcfly1', 'Black-capped Flycatcher'),
('blkpho', 'Black Phoebe'),
('easpho', 'Eastern Phoebe'),
('saypho', 'Say''s Phoebe'),
('nosfly1', 'Northern Scrub-Flycatcher'),
('verfly', 'Vermilion Flycatcher'),
('piwtyr1', 'Pied Water-Tyrant'),
('lottyr1', 'Long-tailed Tyrant'),
('flafly1', 'Flammulated Flycatcher'),
('brratt1', 'Bright-rumped Attila'),
('siryst3', 'Choco Sirystes'),
('rufmou1', 'Rufous Mourner'),
('yucfly1', 'Yucatan Flycatcher'),
('sadfly1', 'Sad Flycatcher'),
('ducfly', 'Dusky-capped Flycatcher'),
('panfly1', 'Panama Flycatcher'),
('astfly', 'Ash-throated Flycatcher'),
('nutfly1', 'Nutting''s Flycatcher'),
('nutfly2', 'Salvadoran Flycatcher'),
('grcfly', 'Great Crested Flycatcher'),
('bncfly', 'Brown-crested Flycatcher'),
('grefly1', 'Grenada Flycatcher'),
('rutfly1', 'Rufous-tailed Flycatcher'),
('lasfly', 'La Sagra''s Flycatcher'),
('stofly1', 'Stolid Flycatcher'),
('purfly1', 'Puerto Rican Flycatcher'),
('leafly1', 'Lesser Antillean Flycatcher'),
('cattyr', 'Cattle Tyrant'),
('leskis1', 'Lesser Kiskadee'),
('grekis', 'Great Kiskadee'),
('bobfly1', 'Boat-billed Flycatcher'),
('rumfly1', 'Rusty-margined Flycatcher'),
('socfly1', 'Social Flycatcher'),
('grcfly1', 'Gray-capped Flycatcher'),
('whrfly', 'White-ringed Flycatcher'),
('gobfly1', 'Golden-bellied Flycatcher'),
('strfly1', 'Streaked Flycatcher'),
('subfly', 'Sulphur-bellied Flycatcher'),
('pirfly1', 'Piratic Flycatcher'),
('trokin', 'Tropical Kingbird'),
('coukin', 'Couch''s Kingbird'),
('caskin', 'Cassin''s Kingbird'),
('thbkin', 'Thick-billed Kingbird'),
('weskin', 'Western Kingbird'),
('easkin', 'Eastern Kingbird'),
('grykin', 'Gray Kingbird'),
('logkin', 'Loggerhead Kingbird'),
('giakin1', 'Giant Kingbird'),
('sctfly', 'Scissor-tailed Flycatcher'),
('fotfly', 'Fork-tailed Flycatcher'),
('rubpep1', 'Rufous-browed Peppershrike'),
('scrgre1', 'Scrub Greenlet'),
('cssvir1', 'Chestnut-sided Shrike-Vireo'),
('grsvir1', 'Green Shrike-Vireo'),
('ybsvir1', 'Yellow-browed Shrike-Vireo'),
('tacgre2', 'Ochre-crowned Greenlet'),
('lesgre1', 'Lesser Greenlet'),
('gofgre1', 'Golden-fronted Greenlet'),
('golvir1', 'Golden Vireo'),
('blmvir1', 'Blue Mountain Vireo'),
('slavir1', 'Slaty Vireo'),
('bkcvir1', 'Black-capped Vireo'),
('dwavir1', 'Dwarf Vireo'),
('whevir', 'White-eyed Vireo'),
('thbvir', 'Thick-billed Vireo'),
('manvir1', 'Mangrove Vireo'),
('cozvir1', 'Cozumel Vireo'),
('stavir1', 'San Andres Vireo'),
('jamvir1', 'Jamaican Vireo'),
('cubvir1', 'Cuban Vireo'),
('purvir1', 'Puerto Rican Vireo'),
('flbvir1', 'Flat-billed Vireo'),
('belvir', 'Bell''s Vireo'),
('gryvir', 'Gray Vireo'),
('hutvir', 'Hutton''s Vireo'),
('yetvir', 'Yellow-throated Vireo'),
('yewvir1', 'Yellow-winged Vireo'),
('casvir', 'Cassin''s Vireo'),
('buhvir', 'Blue-headed Vireo'),
('plsvir', 'Plumbeous Vireo'),
('phivir', 'Philadelphia Vireo'),
('eawvir1', 'Eastern Warbling Vireo'),
('wewvir2', 'Western Warbling Vireo'),
('brcvir1', 'Brown-capped Vireo'),
('reevir1', 'Red-eyed Vireo'),
('yegvir', 'Yellow-green Vireo'),
('bkwvir', 'Black-whiskered Vireo'),
('yucvir', 'Yucatan Vireo'),
('elepai', 'Hawaii Elepaio'),
('elepai5', 'Kauai Elepaio'),
('elepai4', 'Oahu Elepaio'),
('logshr', 'Loggerhead Shrike'),
('norshr4', 'Northern Shrike'),
('gryjay', 'Canada Jay'),
('whtjay1', 'White-throated Jay'),
('dwajay1', 'Dwarf Jay'),
('bltjay1', 'Black-throated Jay'),
('sitjay1', 'Silvery-throated Jay'),
('azhjay1', 'Azure-hooded Jay'),
('btmjay', 'Black-throated Magpie-Jay'),
('wtmjay1', 'White-throated Magpie-Jay'),
('brnjay', 'Brown Jay'),
('grnjay', 'Green Jay'),
('bucjay1', 'Bushy-crested Jay'),
('yucjay1', 'Yucatan Jay'),
('pubjay1', 'Purplish-backed Jay'),
('sabjay', 'San Blas Jay'),
('tufjay1', 'Tufted Jay'),
('blcjay1', 'Black-chested Jay'),
('pinjay', 'Pinyon Jay'),
('stejay', 'Steller''s Jay'),
('blujay', 'Blue Jay'),
('flsjay', 'Florida Scrub-Jay'),
('issjay', 'Island Scrub-Jay'),
('cowscj1', 'California Scrub-Jay'),
('wooscj2', 'Woodhouse''s Scrub-Jay'),
('mexjay4', 'Mexican Jay'),
('mexjay3', 'Transvolcanic Jay'),
('unijay1', 'Unicolored Jay'),
('bkbmag1', 'Black-billed Magpie'),
('yebmag', 'Yellow-billed Magpie'),
('clanut', 'Clark''s Nutcracker'),
('amecro', 'American Crow'),
('cupcro1', 'Cuban Palm-Crow'),
('palcro1', 'Hispaniolan Palm-Crow'),
('cubcro1', 'Cuban Crow'),
('whncro1', 'White-necked Crow'),
('jamcro1', 'Jamaican Crow'),
('tamcro', 'Tamaulipas Crow'),
('sincro1', 'Sinaloa Crow'),
('fiscro', 'Fish Crow'),
('hawcro', 'Hawaiian Crow'),
('chirav', 'Chihuahuan Raven'),
('comrav', 'Common Raven'),
('carchi', 'Carolina Chickadee'),
('bkcchi', 'Black-capped Chickadee'),
('mouchi', 'Mountain Chickadee'),
('mexchi', 'Mexican Chickadee'),
('chbchi', 'Chestnut-backed Chickadee'),
('borchi2', 'Boreal Chickadee'),
('gyhchi', 'Gray-headed Chickadee'),
('britit', 'Bridled Titmouse'),
('oaktit', 'Oak Titmouse'),
('juntit1', 'Juniper Titmouse'),
('tuftit', 'Tufted Titmouse'),
('blctit4', 'Black-crested Titmouse'),
('verdin', 'Verdin'),
('skylar', 'Eurasian Skylark'),
('horlar', 'Horned Lark'),
('miller', 'Millerbird'),
('bkcdon', 'Black-capped Donacobius'),
('banswa', 'Bank Swallow'),
('treswa', 'Tree Swallow'),
('manswa1', 'Mangrove Swallow'),
('golswa1', 'Golden Swallow'),
('vigswa', 'Violet-green Swallow'),
('bahswa', 'Bahama Swallow'),
('purmar', 'Purple Martin'),
('cubmar', 'Cuban Martin'),
('carmar1', 'Caribbean Martin'),
('sinmar1', 'Sinaloa Martin'),
('gybmar', 'Gray-breasted Martin'),
('soumar', 'Southern Martin'),
('brcmar1', 'Brown-chested Martin'),
('nrwswa', 'Northern Rough-winged Swallow'),
('srwswa1', 'Southern Rough-winged Swallow'),
('blcswa1', 'Black-capped Swallow'),
('whtswa1', 'White-thighed Swallow'),
('bawswa1', 'Blue-and-white Swallow'),
('barswa', 'Barn Swallow'),
('cliswa', 'Cliff Swallow'),
('cavswa', 'Cave Swallow'),
('rewbul', 'Red-whiskered Bulbul'),
('revbul', 'Red-vented Bulbul'),
('arcwar1', 'Arctic Warbler'),
('jabwar', 'Japanese Bush Warbler'),
('bushti', 'Bushtit'),
('wrenti', 'Wrentit'),
('warwhe1', 'Warbling White-eye'),
('reblei', 'Red-billed Leiothrix'),
('melthr', 'Chinese Hwamei'),
('gnlthr', 'Greater Necklaced Laughingthrush'),
('ruckin', 'Ruby-crowned Kinglet'),
('gockin', 'Golden-crowned Kinglet'),
('whbnut', 'White-breasted Nuthatch'),
('pygnut', 'Pygmy Nuthatch'),
('bnhnut', 'Brown-headed Nuthatch'),
('bnhnut2', 'Bahama Nuthatch'),
('rebnut', 'Red-breasted Nuthatch'),
('brncre', 'Brown Creeper'),
('tafgna1', 'Tawny-faced Gnatwren'),
('lobgna5', 'Long-billed Gnatwren'),
('sltgna1', 'Slate-throated Gnatcatcher'),
('cubgna1', 'Cuban Gnatcatcher'),
('whlgna3', 'Yucatan Gnatcatcher'),
('trogna2', 'White-browed Gnatcatcher'),
('buggna', 'Blue-gray Gnatcatcher'),
('bktgna', 'Black-tailed Gnatcatcher'),
('calgna', 'California Gnatcatcher'),
('bkcgna', 'Black-capped Gnatcatcher'),
('whlgna2', 'White-lored Gnatcatcher'),
('rocwre', 'Rock Wren'),
('nigwre1', 'Nightingale Wren'),
('scbwre1', 'Scaly-breasted Wren'),
('canwre', 'Canyon Wren'),
('sumwre1', 'Sumichrast''s Wren'),
('navwre1', 'Nava''s Wren'),
('zapwre1', 'Zapata Wren'),
('houwre', 'Northern House Wren'),
('houwre3', 'Cozumel Wren'),
('cinwre1', 'Kalinago Wren'),
('houwre8', 'St. Lucia Wren'),
('houwre10', 'St. Vincent Wren'),
('houwre11', 'Grenada Wren'),
('houwre4', 'Southern House Wren'),
('socwre2', 'Socorro Wren'),
('clawre1', 'Clarion Wren'),
('rubwre2', 'Rufous-browed Wren'),
('ochwre1', 'Ochraceous Wren'),
('pacwre1', 'Pacific Wren'),
('winwre3', 'Winter Wren'),
('timwre1', 'Timberline Wren'),
('sedwre1', 'Sedge Wren'),
('sedwre', 'Grass Wren'),
('marwre', 'Marsh Wren'),
('carwre', 'Carolina Wren'),
('bewwre', 'Bewick''s Wren'),
('whhwre1', 'White-headed Wren'),
('babwre1', 'Band-backed Wren'),
('grbwre1', 'Gray-barred Wren'),
('giawre1', 'Giant Wren'),
('runwre3', 'Russet-naped Wren'),
('runwre2', 'Veracruz Wren'),
('runwre4', 'Rufous-backed Wren'),
('spowre1', 'Spotted Wren'),
('bouwre1', 'Boucard''s Wren'),
('yucwre1', 'Yucatan Wren'),
('cacwre', 'Cactus Wren'),
('bicwre1', 'Bicolored Wren'),
('sohwre1', 'Sooty-headed Wren'),
('blbwre1', 'Black-bellied Wren'),
('rubwre1', 'Rufous-breasted Wren'),
('spbwre1', 'Spot-breasted Wren'),
('hapwre1', 'Happy Wren'),
('bltwre1', 'Black-throated Wren'),
('sinwre1', 'Sinaloa Wren'),
('banwre1', 'Banded Wren'),
('rawwre1', 'Rufous-and-white Wren'),
('stbwre1', 'Stripe-breasted Wren'),
('sttwre1', 'Stripe-throated Wren'),
('plawre1', 'Cabanis''s Wren'),
('plawre3', 'Canebrake Wren'),
('istwre1', 'Isthmian Wren'),
('rivwre1', 'Riverside Wren'),
('baywre1', 'Bay Wren'),
('bubwre1', 'Buff-breasted Wren'),
('whbwre1', 'White-bellied Wren'),
('wbwwre1', 'White-breasted Wood-Wren'),
('gbwwre1', 'Gray-breasted Wood-Wren'),
('sonwre1', 'Song Wren'),
('amedip', 'American Dipper'),
('eursta', 'European Starling'),
('commyn', 'Common Myna'),
('blumoc', 'Blue Mockingbird'),
('bawmoc1', 'Blue-and-white Mockingbird'),
('blacat1', 'Black Catbird'),
('grycat', 'Gray Catbird'),
('whbthr3', 'Martinique Thrasher'),
('whbthr4', 'St. Lucia Thrasher'),
('scbthr', 'Scaly-breasted Thrasher'),
('peethr1', 'Pearly-eyed Thrasher'),
('brotre1', 'Brown Trembler'),
('gratre1', 'Gray Trembler'),
('cubthr', 'Curve-billed Thrasher'),
('ocethr1', 'Ocellated Thrasher'),
('brnthr', 'Brown Thrasher'),
('lobthr', 'Long-billed Thrasher'),
('cozthr1', 'Cozumel Thrasher'),
('benthr', 'Bendire''s Thrasher'),
('grathr1', 'Gray Thrasher'),
('calthr', 'California Thrasher'),
('lecthr', 'LeConte''s Thrasher'),
('crithr', 'Crissal Thrasher'),
('sagthr', 'Sage Thrasher'),
('bahmoc', 'Bahama Mockingbird'),
('socmoc1', 'Socorro Mockingbird'),
('tromoc', 'Tropical Mockingbird'),
('normoc', 'Northern Mockingbird'),
('easblu', 'Eastern Bluebird'),
('wesblu', 'Western Bluebird'),
('moublu', 'Mountain Bluebird'),
('towsol', 'Townsend''s Solitaire'),
('brbsol1', 'Brown-backed Solitaire'),
('cubsol1', 'Cuban Solitaire'),
('rutsol1', 'Rufous-throated Solitaire'),
('blfsol1', 'Black-faced Solitaire'),
('varsol1', 'Varied Solitaire'),
('slcsol1', 'Slate-colored Solitaire'),
('kamao', 'Kamao'),
('olomao', 'Olomao'),
('omao', 'Omao'),
('puaioh', 'Puaiohi'),
('varthr', 'Varied Thrush'),
('bbnthr1', 'Black-billed Nightingale-Thrush'),
('obnthr1', 'Orange-billed Nightingale-Thrush'),
('sbnthr1', 'Slaty-backed Nightingale-Thrush'),
('runthr1', 'Russet Nightingale-Thrush'),
('rcnthr1', 'Ruddy-capped Nightingale-Thrush'),
('bhnthr1', 'Black-headed Nightingale-Thrush'),
('spnthr1', 'Yellow-throated Nightingale-Thrush'),
('veery', 'Veery'),
('gycthr', 'Gray-cheeked Thrush'),
('bicthr', 'Bicknell''s Thrush'),
('swathr', 'Swainson''s Thrush'),
('herthr', 'Hermit Thrush'),
('woothr', 'Wood Thrush'),
('aztthr', 'Aztec Thrush'),
('redwin', 'Redwing'),
('eyethr', 'Eyebrowed Thrush'),
('fieldf', 'Fieldfare'),
('whcthr1', 'White-chinned Thrush'),
('relthr1', 'Western Red-legged Thrush'),
('relthr3', 'Eastern Red-legged Thrush'),
('blarob1', 'Black Thrush'),
('soorob1', 'Sooty Thrush'),
('rucrob1', 'Rufous-collared Robin'),
('amerob', 'American Robin'),
('rubrob', 'Rufous-backed Robin'),
('mourob1', 'Mountain Thrush'),
('lasthr1', 'La Selle Thrush'),
('whethr1', 'White-eyed Thrush'),
('forthr1', 'Forest Thrush'),
('pavthr1', 'Pale-vented Thrush'),
('whtrob1', 'White-throated Thrush'),
('whtthr2', 'Dagua Thrush'),
('cocthr1', 'Cocoa Thrush'),
('baerob1', 'Spectacled Thrush'),
('clcrob', 'Clay-colored Thrush'),
('whrsha', 'White-rumped Shama'),
('blueth', 'Bluethroat'),
('norwhe', 'Northern Wheatear'),
('bohwax', 'Bohemian Waxwing'),
('cedwax', 'Cedar Waxwing'),
('bayfly1', 'Black-and-yellow Silky-flycatcher'),
('grsfly1', 'Gray Silky-flycatcher'),
('ltsfly1', 'Long-tailed Silky-flycatcher'),
('phaino', 'Phainopepla'),
('palmch1', 'Palmchat'),
('oliwar', 'Olive Warbler'),
('vilwea1', 'Village Weaver'),
('orabis1', 'Northern Red Bishop'),
('yecbis', 'Yellow-crowned Bishop'),
('broman1', 'Bronze Mannikin'),
('afrsil1', 'African Silverbill'),
('indsil', 'Indian Silverbill'),
('javspa', 'Java Sparrow'),
('nutman', 'Scaly-breasted Munia'),
('trimun', 'Tricolored Munia'),
('chemun', 'Chestnut Munia'),
('lavwax', 'Lavender Waxbill'),
('orcwax', 'Orange-cheeked Waxbill'),
('comwax', 'Common Waxbill'),
('bkrwax', 'Black-rumped Waxbill'),
('redava', 'Red Avadavat'),
('pitwhy', 'Pin-tailed Whydah'),
('houspa', 'House Sparrow'),
('eutspa', 'Eurasian Tree Sparrow'),
('eaywag', 'Eastern Yellow Wagtail'),
('whiwag', 'White Wagtail'),
('meapip1', 'Meadow Pipit'),
('retpip', 'Red-throated Pipit'),
('sibpip1', 'Siberian Pipit'),
('amepip', 'American Pipit'),
('sprpip', 'Sprague''s Pipit'),
('yelpip2', 'Yellowish Pipit'),
('brambl', 'Brambling'),
('eleeup1', 'Elegant Euphonia'),
('anteup2', 'Hispaniolan Euphonia'),
('anteup3', 'Puerto Rican Euphonia'),
('anteup4', 'Lesser Antillean Euphonia'),
('blcchl1', 'Blue-crowned Chlorophonia'),
('gobchl1', 'Golden-browed Chlorophonia'),
('jameup1', 'Jamaican Euphonia'),
('screup3', 'West Mexican Euphonia'),
('screup1', 'Scrub Euphonia'),
('yeceup1', 'Yellow-crowned Euphonia'),
('whveup1', 'White-vented Euphonia'),
('yeteup1', 'Yellow-throated Euphonia'),
('thbeup1', 'Thick-billed Euphonia'),
('spceup1', 'Spot-crowned Euphonia'),
('olbeup1', 'Olive-backed Euphonia'),
('fuveup1', 'Fulvous-vented Euphonia'),
('taceup1', 'Tawny-capped Euphonia'),
('orbeup1', 'Orange-bellied Euphonia'),
('hoogro1', 'Hooded Grosbeak'),
('evegro', 'Evening Grosbeak'),
('poouli', 'Poo-uli'),
('akikik', 'Akikiki'),
('oahala', 'Oahu Alauahio'),
('kakawa', 'Kakawahie'),
('mauala', 'Maui Alauahio'),
('palila', 'Palila'),
('layfin', 'Laysan Finch'),
('nihfin', 'Nihoa Finch'),
('crehon', 'Akohekohe'),
('apapan', 'Apapane'),
('iiwi', 'Iiwi'),
('ou', 'Ou'),
('maupar', 'Maui Parrotbill'),
('nukupu2', 'Kauai Nukupuu'),
('nukupu1', 'Maui Nukupuu'),
('akiapo', 'Akiapolaau'),
('greaki4', 'Kauai Akialoa'),
('aniani', 'Anianiau'),
('hawama', 'Hawaii Amakihi'),
('oahama', 'Oahu Amakihi'),
('kauama', 'Kauai Amakihi'),
('hawcre', 'Hawaii Creeper'),
('akekee', 'Akekee'),
('akepa1', 'Hawaii Akepa'),
('akepa2', 'Oahu Akepa'),
('akepa3', 'Maui Akepa'),
('comros', 'Common Rosefinch'),
('pingro', 'Pine Grosbeak'),
('gcrfin', 'Gray-crowned Rosy-Finch'),
('bkrfin', 'Black Rosy-Finch'),
('bcrfin', 'Brown-capped Rosy-Finch'),
('houfin', 'House Finch'),
('purfin', 'Purple Finch'),
('casfin', 'Cassin''s Finch'),
('yefcan', 'Yellow-fronted Canary'),
('redpol1', 'Redpoll'),
('redcro', 'Red Crossbill'),
('redcro9', 'Cassia Crossbill'),
('hiscro', 'Hispaniolan Crossbill'),
('whwcro', 'White-winged Crossbill'),
('eurgol', 'European Goldfinch'),
('comcan', 'Island Canary'),
('pinsis', 'Pine Siskin'),
('blcsis1', 'Black-capped Siskin'),
('blhsis1', 'Black-headed Siskin'),
('antsis1', 'Antillean Siskin'),
('lesgol', 'Lesser Goldfinch'),
('lawgol', 'Lawrence''s Goldfinch'),
('amegfi', 'American Goldfinch'),
('yebsis1', 'Yellow-bellied Siskin'),
('redsis1', 'Red Siskin'),
('laplon', 'Lapland Longspur'),
('chclon', 'Chestnut-collared Longspur'),
('smilon', 'Smith''s Longspur'),
('mcclon', 'Thick-billed Longspur'),
('snobun', 'Snow Bunting'),
('mckbun', 'McKay''s Bunting'),
('rottan2', 'Rosy Thrush-Tanager'),
('ytbtan1', 'Yellow-throated Chlorospingus'),
('atbtan1', 'Ashy-throated Chlorospingus'),
('scbtan1', 'Sooty-capped Chlorospingus'),
('cobtan1', 'Common Chlorospingus'),
('tabtan1', 'Tacarcuna Chlorospingus'),
('pibtan1', 'Pirre Chlorospingus'),
('ruwspa', 'Rufous-winged Sparrow'),
('citspa1', 'Cinnamon-tailed Sparrow'),
('sthspa1', 'Stripe-headed Sparrow'),
('blcspa1', 'Black-chested Sparrow'),
('brispa1', 'Bridled Sparrow'),
('botspa', 'Botteri''s Sparrow'),
('casspa', 'Cassin''s Sparrow'),
('bacspa', 'Bachman''s Sparrow'),
('graspa', 'Grasshopper Sparrow'),
('olispa', 'Olive Sparrow'),
('grbspa1', 'Green-backed Sparrow'),
('blsspa1', 'Black-striped Sparrow'),
('chispa', 'Chipping Sparrow'),
('clcspa', 'Clay-colored Sparrow'),
('bkcspa', 'Black-chinned Sparrow'),
('fiespa', 'Field Sparrow'),
('brespa', 'Brewer''s Sparrow'),
('worspa', 'Worthen''s Sparrow'),
('fisspa', 'Five-striped Sparrow'),
('bktspa', 'Black-throated Sparrow'),
('larspa', 'Lark Sparrow'),
('larbun', 'Lark Bunting'),
('sthbrf3', 'Costa Rican Brushfinch'),
('sthbrf1', 'Black-headed Brushfinch'),
('orbspa1', 'Orange-billed Sparrow'),
('gsbfin1', 'Green-striped Brushfinch'),
('ccbfin', 'Chestnut-capped Brushfinch'),
('soffin1', 'Sooty-faced Finch'),
('amtspa', 'American Tree Sparrow'),
('foxspa', 'Fox Sparrow'),
('daejun', 'Dark-eyed Junco'),
('daejun2', 'Guadalupe Junco'),
('yeejun', 'Yellow-eyed Junco'),
('yeejun2', 'Baird''s Junco'),
('voljun1', 'Volcano Junco'),
('rucspa1', 'Rufous-collared Sparrow'),
('whcspa', 'White-crowned Sparrow'),
('gocspa', 'Golden-crowned Sparrow'),
('harspa', 'Harris''s Sparrow'),
('whtspa', 'White-throated Sparrow'),
('sagspa1', 'Sagebrush Sparrow'),
('belspa2', 'Bell''s Sparrow'),
('strspa1', 'Striped Sparrow'),
('vesspa', 'Vesper Sparrow'),
('lecspa', 'LeConte''s Sparrow'),
('seaspa', 'Seaside Sparrow'),
('nstspa', 'Nelson''s Sparrow'),
('sstspa', 'Saltmarsh Sparrow'),
('savspa', 'Savannah Sparrow'),
('baispa', 'Baird''s Sparrow'),
('henspa', 'Henslow''s Sparrow'),
('simspa1', 'Sierra Madre Sparrow'),
('sonspa', 'Song Sparrow'),
('linspa', 'Lincoln''s Sparrow'),
('swaspa', 'Swamp Sparrow'),
('laffin1', 'Large-footed Finch'),
('zapspa1', 'Zapata Sparrow'),
('rcgspa1', 'Rusty-crowned Ground-Sparrow'),
('cantow', 'Canyon Towhee'),
('whttow1', 'White-throated Towhee'),
('abetow', 'Abert''s Towhee'),
('caltow', 'California Towhee'),
('whegrs2', 'White-eared Ground-Sparrow'),
('pregrs1', 'White-faced Ground-Sparrow'),
('pregrs2', 'Cabanis''s Ground-Sparrow'),
('russpa1', 'Rusty Sparrow'),
('rucspa', 'Rufous-crowned Sparrow'),
('oaxspa1', 'Oaxaca Sparrow'),
('gnttow', 'Green-tailed Towhee'),
('spotow', 'Spotted Towhee'),
('eastow', 'Eastern Towhee'),
('coltow1', 'Collared Towhee'),
('rcbfin1', 'Rufous-capped Brushfinch'),
('wnbfin1', 'White-naped Brushfinch'),
('yetfin1', 'Yellow-thighed Brushfinch'),
('yegfin1', 'Yellow-green Brushfinch'),
('wectan1', 'Western Chat-Tanager'),
('eactan1', 'Eastern Chat-Tanager'),
('bcptan1', 'Black-crowned Palm-Tanager'),
('gcptan1', 'Gray-crowned Palm-Tanager'),
('whwwar1', 'White-winged Warbler'),
('grtwar1', 'Green-tailed Warbler'),
('purtan1', 'Puerto Rican Tanager'),
('wesspi', 'Western Spindalis'),
('jamspi', 'Jamaican Spindalis'),
('hisspi', 'Hispaniolan Spindalis'),
('purspi', 'Puerto Rican Spindalis'),
('wrenth1', 'Wrenthrush'),
('yehwar1', 'Yellow-headed Warbler'),
('oriwar1', 'Oriente Warbler'),
('yebcha', 'Yellow-breasted Chat'),
('yehbla', 'Yellow-headed Blackbird'),
('boboli', 'Bobolink'),
('wesmea', 'Western Meadowlark'),
('easmea', 'Eastern Meadowlark'),
('lilmea2', 'Chihuahuan Meadowlark'),
('rebbla1', 'Red-breasted Meadowlark'),
('yebcac1', 'Yellow-billed Cacique'),
('yewcac1', 'Yellow-winged Cacique'),
('creoro1', 'Crested Oropendola'),
('chhoro1', 'Chestnut-headed Oropendola'),
('monoro1', 'Montezuma Oropendola'),
('blaoro1', 'Black Oropendola'),
('scrcac1', 'Scarlet-rumped Cacique'),
('yercac1', 'Yellow-rumped Cacique'),
('graori1', 'Hispaniolan Oriole'),
('graori2', 'Cuban Oriole'),
('graori3', 'Bahama Oriole'),
('graori4', 'Puerto Rican Oriole'),
('stlori1', 'St. Lucia Oriole'),
('monori1', 'Montserrat Oriole'),
('marori1', 'Martinique Oriole'),
('bkvori', 'Black-vented Oriole'),
('bawori1', 'Bar-winged Oriole'),
('bkcori', 'Black-cowled Oriole'),
('orcori', 'Orchard Oriole'),
('hooori', 'Hooded Oriole'),
('yebori1', 'Yellow-backed Oriole'),
('orcori1', 'Orange-crowned Oriole'),
('yetori1', 'Yellow-tailed Oriole'),
('ventro1', 'Venezuelan Troupial'),
('stbori', 'Streak-backed Oriole'),
('bulori', 'Bullock''s Oriole'),
('oraori1', 'Orange Oriole'),
('jamori1', 'Jamaican Oriole'),
('spbori', 'Spot-breasted Oriole'),
('altori', 'Altamira Oriole'),
('audori', 'Audubon''s Oriole'),
('balori', 'Baltimore Oriole'),
('blbori1', 'Black-backed Oriole'),
('scoori', 'Scott''s Oriole'),
('jambla1', 'Jamaican Blackbird'),
('rewbla', 'Red-winged Blackbird'),
('resbla1', 'Red-shouldered Blackbird'),
('tribla', 'Tricolored Blackbird'),
('tasbla', 'Tawny-shouldered Blackbird'),
('yesbla1', 'Yellow-shouldered Blackbird'),
('shicow', 'Shiny Cowbird'),
('brocow', 'Bronzed Cowbird'),
('bnhcow', 'Brown-headed Cowbird'),
('giacow', 'Giant Cowbird'),
('melbla1', 'Melodious Blackbird'),
('cubbla', 'Cuban Blackbird'),
('rusbla', 'Rusty Blackbird'),
('brebla', 'Brewer''s Blackbird'),
('comgra', 'Common Grackle'),
('botgra', 'Boat-tailed Grackle'),
('grtgra', 'Great-tailed Grackle'),
('nicgra1', 'Nicaraguan Grackle'),
('gragra1', 'Greater Antillean Grackle'),
('cargra1', 'Carib Grackle'),
('yehbla2', 'Yellow-hooded Blackbird'),
('ovenbi1', 'Ovenbird'),
('woewar1', 'Worm-eating Warbler'),
('louwat', 'Louisiana Waterthrush'),
('norwat', 'Northern Waterthrush'),
('gowwar', 'Golden-winged Warbler'),
('buwwar', 'Blue-winged Warbler'),
('bawwar', 'Black-and-white Warbler'),
('prowar', 'Prothonotary Warbler'),
('swawar', 'Swainson''s Warbler'),
('crcwar', 'Crescent-chested Warbler'),
('fltwar1', 'Flame-throated Warbler'),
('tenwar', 'Tennessee Warbler'),
('orcwar', 'Orange-crowned Warbler'),
('colwar', 'Colima Warbler'),
('lucwar', 'Lucy''s Warbler'),
('naswar', 'Nashville Warbler'),
('virwar', 'Virginia''s Warbler'),
('semwar1', 'Semper''s Warbler'),
('conwar', 'Connecticut Warbler'),
('gycyel', 'Gray-crowned Yellowthroat'),
('macwar', 'MacGillivray''s Warbler'),
('mouwar', 'Mourning Warbler'),
('kenwar', 'Kentucky Warbler'),
('olcyel1', 'Olive-crowned Yellowthroat'),
('blpyel1', 'Black-polled Yellowthroat'),
('belyel1', 'Belding''s Yellowthroat'),
('bahyel1', 'Bahama Yellowthroat'),
('altyel1', 'Altamira Yellowthroat'),
('comyel', 'Common Yellowthroat'),
('hooyel1', 'Hooded Yellowthroat'),
('whiwar1', 'Whistling Warbler'),
('pluwar1', 'Plumbeous Warbler'),
('elwwar1', 'Elfin-woods Warbler'),
('arrwar1', 'Arrowhead Warbler'),
('hoowar', 'Hooded Warbler'),
('amered', 'American Redstart'),
('kirwar', 'Kirtland''s Warbler'),
('camwar', 'Cape May Warbler'),
('cerwar', 'Cerulean Warbler'),
('norpar', 'Northern Parula'),
('tropar', 'Tropical Parula'),
('magwar', 'Magnolia Warbler'),
('babwar', 'Bay-breasted Warbler'),
('bkbwar', 'Blackburnian Warbler'),
('yelwar1', 'Northern Yellow Warbler'),
('manwar1', 'Mangrove Yellow Warbler'),
('chswar', 'Chestnut-sided Warbler'),
('bkpwar', 'Blackpoll Warbler'),
('btbwar', 'Black-throated Blue Warbler'),
('palwar', 'Palm Warbler'),
('olcwar1', 'Olive-capped Warbler'),
('pinwar', 'Pine Warbler'),
('yerwar', 'Yellow-rumped Warbler'),
('yetwar', 'Yellow-throated Warbler'),
('yetwar3', 'Bahama Warbler'),
('vitwar1', 'Vitelline Warbler'),
('prawar', 'Prairie Warbler'),
('adewar1', 'Adelaide''s Warbler'),
('barwar', 'Barbuda Warbler'),
('stlwar', 'St. Lucia Warbler'),
('grawar', 'Grace''s Warbler'),
('btywar', 'Black-throated Gray Warbler'),
('towwar', 'Townsend''s Warbler'),
('herwar', 'Hermit Warbler'),
('gchwar', 'Golden-cheeked Warbler'),
('btnwar', 'Black-throated Green Warbler'),
('fatwar', 'Fan-tailed Warbler'),
('rucwar', 'Rufous-capped Warbler'),
('rucwar4', 'Chestnut-capped Warbler'),
('blcwar1', 'Black-cheeked Warbler'),
('pirwar1', 'Pirre Warbler'),
('gobwar1', 'Golden-browed Warbler'),
('gcrwar', 'Golden-crowned Warbler'),
('thswar5', 'Costa Rican Warbler'),
('thswar9', 'Tacarcuna Warbler'),
('burwar1', 'Buff-rumped Warbler'),
('canwar', 'Canada Warbler'),
('wlswar', 'Wilson''s Warbler'),
('refwar', 'Red-faced Warbler'),
('redwar1', 'Red Warbler'),
('pihwar1', 'Pink-headed Warbler'),
('paired', 'Painted Redstart'),
('sltred', 'Slate-throated Redstart'),
('colred1', 'Collared Redstart'),
('duftan1', 'Dusky-faced Tanager'),
('rottan1', 'Rose-throated Tanager'),
('heptan', 'Hepatic Tanager'),
('sumtan', 'Summer Tanager'),
('scatan', 'Scarlet Tanager'),
('westan', 'Western Tanager'),
('flctan', 'Flame-colored Tanager'),
('whwtan1', 'White-winged Tanager'),
('rehtan1', 'Red-headed Tanager'),
('rcatan1', 'Red-crowned Ant-Tanager'),
('rtatan1', 'Red-throated Ant-Tanager'),
('bcatan1', 'Black-cheeked Ant-Tanager'),
('olitan1', 'Carmiol''s Tanager'),
('lestan', 'Lemon-spectacled Tanager'),
('crcgro', 'Crimson-collared Grosbeak'),
('blfgro1', 'Black-faced Grosbeak'),
('yeggro1', 'Yellow-green Grosbeak'),
('norcar', 'Northern Cardinal'),
('pyrrhu', 'Pyrrhuloxia'),
('yelgro', 'Yellow Grosbeak'),
('bltgro1', 'Black-thighed Grosbeak'),
('robgro', 'Rose-breasted Grosbeak'),
('bkhgro', 'Black-headed Grosbeak'),
('rebcha1', 'Red-breasted Chat'),
('grtcha1', 'Gray-throated Chat'),
('blusee1', 'Blue Seedeater'),
('bubgro1', 'Blue-black Grosbeak'),
('blubun', 'Blue Bunting'),
('blugrb1', 'Blue Grosbeak'),
('lazbun', 'Lazuli Bunting'),
('indbun', 'Indigo Bunting'),
('robbun1', 'Rose-bellied Bunting'),
('orbbun1', 'Orange-breasted Bunting'),
('varbun', 'Varied Bunting'),
('paibun', 'Painted Bunting'),
('dickci', 'Dickcissel'),
('reccar', 'Red-crested Cardinal'),
('yebcar', 'Yellow-billed Cardinal'),
('grhtan1', 'Gray-headed Tanager'),
('whstan1', 'White-shouldered Tanager'),
('tactan1', 'Tawny-crested Tanager'),
('whltan1', 'White-lined Tanager'),
('btstan1', 'Black-throated Shrike-Tanager'),
('wtstan1', 'White-throated Shrike-Tanager'),
('crctan1', 'Crimson-collared Tanager'),
('flrtan1', 'Flame-rumped Tanager'),
('y00599', 'Scarlet-rumped Tanager'),
('crbtan1', 'Crimson-backed Tanager'),
('bagtan1', 'Blue-and-gold Tanager'),
('bugtan', 'Blue-gray Tanager'),
('yewtan1', 'Yellow-winged Tanager'),
('paltan1', 'Palm Tanager'),
('spetan1', 'Speckled Tanager'),
('azrtan1', 'Azure-rumped Tanager'),
('gagtan1', 'Gray-and-gold Tanager'),
('leatan1', 'Lesser Antillean Tanager'),
('gohtan1', 'Golden-hooded Tanager'),
('spctan1', 'Spangle-cheeked Tanager'),
('grntan1', 'Green-naped Tanager'),
('plctan1', 'Plain-colored Tanager'),
('ruwtan1', 'Rufous-winged Tanager'),
('bahtan1', 'Bay-headed Tanager'),
('emetan1', 'Emerald Tanager'),
('sittan1', 'Silver-throated Tanager'),
('swatan1', 'Swallow Tanager'),
('sctdac1', 'Scarlet-thighed Dacnis'),
('bludac1', 'Blue Dacnis'),
('virdac1', 'Viridian Dacnis'),
('shihon1', 'Shining Honeycreeper'),
('purhon1', 'Purple Honeycreeper'),
('relhon1', 'Red-legged Honeycreeper'),
('grehon1', 'Green Honeycreeper'),
('surtan1', 'Sulphur-rumped Tanager'),
('scbtan2', 'Scarlet-browed Tanager'),
('yebtan1', 'Yellow-backed Tanager'),
('baytan2', 'Black-and-yellow Tanager'),
('whecon1', 'White-eared Conebill'),
('cibflo1', 'Cinnamon-bellied Flowerpiercer'),
('slaflo1', 'Slaty Flowerpiercer'),
('slafin1', 'Slaty Finch'),
('pebfin1', 'Peg-billed Finch'),
('saffin', 'Saffron Finch'),
('gryfin1', 'Grassland Yellow-Finch'),
('wtgfin1', 'Wedge-tailed Grass-Finch'),
('blbgra1', 'Blue-black Grassquit'),
('rubsee1', 'Ruddy-breasted Seedeater'),
('tbsfin1', 'Thick-billed Seed-Finch'),
('nisfin1', 'Nicaraguan Seed-Finch'),
('lbsfin1', 'Large-billed Seed-Finch'),
('varsee3', 'Variable Seedeater'),
('whcsee1', 'Morelet''s Seedeater'),
('whcsee2', 'Cinnamon-rumped Seedeater'),
('yebsee1', 'Yellow-bellied Seedeater'),
('slcsee1', 'Slate-colored Seedeater'),
('banana', 'Bananaquit'),
('yefgra1', 'Yellow-faced Grassquit'),
('orange1', 'Orangequit'),
('purbul1', 'Puerto Rican Bullfinch'),
('cubbul2', 'Cuban Bullfinch'),
('cubbul3', 'Grand Cayman Bullfinch'),
('grabul1', 'Greater Antillean Bullfinch'),
('yesgra1', 'Yellow-shouldered Grassquit'),
('cubgra', 'Cuban Grassquit'),
('leabul1', 'Lesser Antillean Bullfinch'),
('barbul1', 'Barbados Bullfinch'),
('slbfin1', 'St. Lucia Black Finch'),
('bkfgra', 'Black-faced Grassquit'),
('cocfin1', 'Cocos Finch'),
('butsal1', 'Buff-throated Saltator'),
('blhsal1', 'Black-headed Saltator'),
('grasal2', 'Cinnamon-bellied Saltator'),
('strsal1', 'Streaked Saltator'),
('leasal1', 'Lesser Antillean Saltator'),
('slcgro1', 'Slate-colored Grosbeak')
on conflict (code) do update set common_name = excluded.common_name;

create table public.push_tokens (
  user_id    uuid not null references auth.users (id) on delete cascade,
  token      text not null,
  platform   text not null check (platform in ('android', 'ios', 'web')),
  updated_at timestamptz not null default now(),
  primary key (user_id, token)
);
alter table public.push_tokens enable row level security;
create policy "own tokens" on public.push_tokens for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table public.notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  kind       text not null check (kind in ('reaction', 'comment', 'friend_request', 'friend_accept')),
  actor_id   uuid references auth.users (id) on delete set null,
  item_kind  text,
  item_id    text,
  owner_id   uuid,
  title      text not null,
  body       text,
  created_at timestamptz not null default now(),
  read_at    timestamptz
);
create index notifications_user_idx on public.notifications (user_id, created_at desc);
alter table public.notifications enable row level security;
create policy "own notifications read" on public.notifications for select to authenticated using (auth.uid() = user_id);
create policy "own notifications update" on public.notifications for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own notifications delete" on public.notifications for delete to authenticated using (auth.uid() = user_id);

-- Private config the triggers read: where to deliver pushes and the shared secret.
create schema if not exists private;
create table if not exists private.push_config (
  key   text primary key,
  value text not null
);
insert into private.push_config (key, value) values
  ('url', 'https://jrrakzicvqjxteelpcjd.supabase.co/functions/v1/push'),
  ('secret', 'df4c9b67d128fd7a1e61f03d9f6075eb25b3b8ef066fff84')
on conflict (key) do update set value = excluded.value;

create or replace function public.display_name_of(u uuid) returns text
language sql stable security definer set search_path = public as $$
  select coalesce(nullif(btrim(p.display_name), ''), case when p.username is not null then '@' || p.username end, 'A friend')
  from public.profiles p where p.id = u;
$$;

create or replace function public.item_label(kind text, item text, owner uuid) returns text
language sql stable security definer set search_path = public as $$
  select case
    when kind = 'catch' then coalesce((select 'your ' || n.common_name from public.sightings s join public.species_names n on n.code = s.species_code where s.id::text = item), 'your catch')
    when kind = 'badge' then 'your ' || replace(item, '-', ' ') || ' badge'
    else 'your post' end;
$$;

-- Insert a notification and hand it to the push function.
create or replace function public.notify(recipient uuid, kind text, actor uuid, item_kind text, item_id text, owner uuid, title text, body text)
returns void language plpgsql security definer set search_path = public, extensions as $$
declare
  n_id uuid;
  cfg_url text;
  cfg_secret text;
begin
  if recipient is null or recipient = actor then return; end if;
  insert into public.notifications (user_id, kind, actor_id, item_kind, item_id, owner_id, title, body)
  values (recipient, kind, actor, item_kind, item_id, owner, title, body) returning id into n_id;
  select value into cfg_url from private.push_config where key = 'url';
  select value into cfg_secret from private.push_config where key = 'secret';
  if cfg_url is not null then
    perform net.http_post(
      url := cfg_url,
      headers := jsonb_build_object('Content-Type', 'application/json', 'x-push-secret', cfg_secret),
      body := jsonb_build_object('notification_id', n_id),
      timeout_milliseconds := 5000
    );
  end if;
end;
$$;

create or replace function public.on_reaction_insert() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  perform public.notify(new.owner_id, 'reaction', new.from_user, new.item_kind, new.item_id, new.owner_id,
    public.display_name_of(new.from_user) || ' congratulated you', 'on ' || public.item_label(new.item_kind, new.item_id, new.owner_id));
  return new;
end;
$$;
create trigger reactions_notify after insert on public.reactions for each row execute function public.on_reaction_insert();

create or replace function public.on_comment_insert() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  r uuid;
  who text := public.display_name_of(new.author_id);
  label text := public.item_label(new.item_kind, new.item_id, new.owner_id);
begin
  -- The item's owner, then everyone else who commented on it.
  for r in
    select new.owner_id
    union
    select c.author_id from public.comments c
    where c.item_kind = new.item_kind and c.item_id = new.item_id and c.owner_id = new.owner_id and c.author_id <> new.author_id
  loop
    if r <> new.author_id then
      perform public.notify(r, 'comment', new.author_id, new.item_kind, new.item_id, new.owner_id,
        who || ' commented on ' || case when r = new.owner_id then label else 'a post you follow' end, left(new.body, 140));
    end if;
  end loop;
  return new;
end;
$$;
create trigger comments_notify after insert on public.comments for each row execute function public.on_comment_insert();

create or replace function public.on_friendship_change() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' and new.status = 'pending' then
    perform public.notify(new.addressee_id, 'friend_request', new.requester_id, null, null, null,
      public.display_name_of(new.requester_id) || ' wants to be friends', 'Open Friends to respond');
  elsif tg_op = 'UPDATE' and new.status = 'accepted' and old.status = 'pending' then
    perform public.notify(new.requester_id, 'friend_accept', new.addressee_id, null, null, null,
      public.display_name_of(new.addressee_id) || ' accepted your friend request', 'You can see each other''s catches now');
  end if;
  return new;
end;
$$;
create trigger friendships_notify after insert or update on public.friendships for each row execute function public.on_friendship_change();

-- Unread count for the tab badge.
create or replace function public.unread_notifications() returns bigint
language sql stable security definer set search_path = public as $$
  select count(*) from public.notifications where user_id = auth.uid() and read_at is null;
$$;
grant execute on function public.unread_notifications() to authenticated;
